export interface BlogPost {
  slug: string
  title: string
  excerpt: string
  metaDescription: string
  category: string
  image: string
  imageAlt: string
  date: string
  dateISO: string
  readTime: string
  featured: boolean
  author: {
    name: string
    role: string
  }
  relatedDestinations: string[]
  relatedSlugs: string[]
  tags: string[]
  sections: ArticleSection[]
}

export interface ArticleSection {
  heading: string
  body: string
  image?: string
  imageAlt?: string
  cta?: {
    text: string
    href: string
  }
}

export const blogPosts: BlogPost[] = [
  {
    slug: "viajar-sola-sin-miedo",
    title: "Viajar sola sin miedo: la guía definitiva para lanzarte",
    excerpt: "¿Quieres viajar pero no tienes con quién? Te contamos cómo dar el paso y por qué un viaje en grupo puede ser la mejor decisión de tu vida.",
    metaDescription: "Guía completa para viajar sola sin miedo en 2026. Descubre cómo los viajes en grupo para jóvenes de 20-35 años eliminan la inseguridad y te conectan con tu comunidad.",
    category: "Inspiración",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Grupo de viajeras jóvenes disfrutando juntas en la playa de Zanzíbar",
    date: "28 Feb 2026",
    dateISO: "2026-02-28",
    readTime: "6 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["zanzibar", "tailandia", "bali"],
    relatedSlugs: ["como-hacer-amigos-viajando", "por-que-viajar-en-grupo"],
    tags: ["viajar sola", "viajes en grupo", "viajes para jóvenes", "viajar sin miedo", "viajes para mujeres"],
    sections: [
      {
        heading: "¿Por qué nos da miedo viajar solas?",
        body: "El miedo a viajar sola no es irracional. Es completamente humano. Nos preocupa la seguridad, el idioma, perdernos, sentirnos aisladas... Pero la realidad es que la mayor barrera no es el destino, es la decisión.\n\nSegún un estudio de Booking.com, el 72% de las mujeres jóvenes en España quieren viajar pero no lo hacen por falta de compañía. No es dinero. No es tiempo. Es no tener con quién ir.\n\nLa buena noticia: no tienes que elegir entre viajar sola o no viajar. Hay una tercera opción.",
      },
      {
        heading: "Viajes en grupo: la solución que no sabías que existía",
        body: "Un viaje en grupo organizado elimina las dos barreras principales: la soledad y la logística. Llegas al aeropuerto, conoces a tu grupo (personas de tu misma edad, 20-35 años) y desde ese momento tienes compañía, plan y un coordinador que se encarga de todo.\n\nNo es un tour de autobús con 50 personas. Es un grupo reducido de 12-18 viajeros con un itinerario diseñado para vivir experiencias reales, no para tachar monumentos.",
        image: "/images/hero-brasil.jpg",
        imageAlt: "Grupo reducido de viajeros jóvenes explorando Brasil juntos",
      },
      {
        heading: "Qué buscar en una agencia de viajes en grupo",
        body: "No todas las agencias son iguales. Si estás pensando en dar el paso, fíjate en estos puntos clave:\n\n• Rango de edad definido — Un grupo de 20-35 años no es lo mismo que uno abierto a todas las edades. La afinidad importa.\n\n• Coordinador en destino — No es lo mismo tener un guía turístico que alguien de la organización que viaja contigo, gestiona imprevistos y se asegura de que el grupo funcione.\n\n• Itinerarios propios — Huye de los paquetes genéricos. Los mejores viajes tienen experiencias locales que no encontrarías por tu cuenta.\n\n• Transparencia de precio — Qué incluye, qué no. Sin letra pequeña.\n\n• Prueba social real — Reseñas, fotos de viajeros anteriores, testimonios con nombre y apellido.",
      },
      {
        heading: "Destinos ideales para tu primer viaje en grupo",
        body: "Si nunca has viajado en grupo, estos destinos son perfectos para empezar:\n\nTailandia — Seguro, económico y con una mezcla brutal de templos, playas y gastronomía. El destino estrella para debutantes.\n\nBali — Espiritualidad, volcanes y arrozales. Ideal si buscas algo transformador.\n\nZanzíbar — Fuera de las rutas masificadas. Playas de arena blanca, cultura swahili y snorkel en aguas cristalinas.\n\nMarruecos — A solo 2 horas de avión desde España. Exótico, cercano y perfecto para un primer contacto con otra cultura.",
        cta: { text: "Ver viajes disponibles", href: "/viajes#resultados" },
      },
      {
        heading: "Testimonios reales: ellas ya se lanzaron",
        body: "Laura, 28 años, Madrid: \"Fui sin conocer a nadie. Volví con gente que ya considero amigos.\"\n\nSara, 24 años, Bilbao: \"Zanzíbar no estaba en mi radar. Ahora es mi viaje favorito de toda la vida.\"\n\nEstas historias no son excepciones. Son la norma. El 98% de las viajeras que van con Travelhood repetirían la experiencia.",
      },
      {
        heading: "El paso más difícil es el primero",
        body: "No necesitas un plan perfecto. No necesitas compañía. No necesitas experiencia previa. Solo necesitas decidir que este año vas a dejar de pensar en viajar y vas a hacerlo.\n\nEl grupo ya se está formando. Solo falta tu nombre en la lista.",
        cta: { text: "Reserva tu plaza ahora", href: "/viajes#resultados" },
      },
    ],
  },
  {
    slug: "destinos-baratos-jovenes",
    title: "10 destinos baratos que todo joven debería visitar antes de los 35",
    excerpt: "Desde el sudeste asiático hasta Latinoamérica, estos son los destinos que más experiencia te dan por cada euro invertido.",
    metaDescription: "Los 10 mejores destinos baratos para jóvenes en 2026. Viajes asequibles en grupo desde España: Tailandia, Marruecos, Perú, Bali y más. Precios y guía completa.",
    category: "Destinos",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Jóvenes viajeros explorando un destino económico en Sudamérica",
    date: "22 Feb 2026",
    dateISO: "2026-02-22",
    readTime: "8 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "marruecos", "peru", "bali", "vietnam"],
    relatedSlugs: ["que-incluye-viaje-grupo", "viajar-sola-sin-miedo"],
    tags: ["destinos baratos", "viajes económicos", "viajes jóvenes", "destinos 2026", "viajes low cost"],
    sections: [
      {
        heading: "No necesitas ser rico para viajar lejos",
        body: "Existe un mito que dice que viajar es caro. Y claro, puede serlo si eliges mal. Pero hay destinos donde tu dinero rinde el triple, donde una cena cuesta 3€ y un bungalow frente al mar 20€ la noche.\n\nLa clave no es cuánto gastas, sino dónde gastas. Y para jóvenes de 20 a 35 años, hay destinos que ofrecen una experiencia brutal a precios accesibles.",
      },
      {
        heading: "1. Tailandia — El clásico imbatible",
        body: "Por algo Tailandia lleva años siendo el destino favorito de los viajeros jóvenes. La comida callejera es espectacular y cuesta entre 1 y 3 euros. Los templos de Bangkok y Chiang Mai son gratuitos o cuestan menos de 5€. Y las playas del sur compiten con las de cualquier resort de lujo.\n\nPrecio medio de un viaje en grupo: desde 1.090€ (sin vuelo).\nVuelo desde España: 500-700€.",
        image: "/images/hero-zanzibar.jpg",
        imageAlt: "Templos y playas de Tailandia, destino económico para jóvenes",
        cta: { text: "Ver viajes a Tailandia", href: "/destino/tailandia" },
      },
      {
        heading: "2. Marruecos — Exótico a 2 horas de avión",
        body: "Si buscas algo diferente sin gastarte un dineral en vuelos, Marruecos es tu destino. Vuelos por 50-150€, riads con encanto desde 15€ la noche y una ruta por el desierto del Sahara que te cambia la perspectiva.\n\nPrecio medio viaje en grupo: desde 590€.\nVuelo: 50-180€.",
        cta: { text: "Ver viajes a Marruecos", href: "/destino/marruecos" },
      },
      {
        heading: "3. Vietnam — Asia auténtica a precio de saldo",
        body: "Vietnam es probablemente el país con mejor relación calidad-precio del mundo. Un phở en la calle por 1€, una cerveza por 0,50€ y la bahía de Ha Long es uno de los paisajes más impresionantes del planeta.\n\nPrecio medio viaje en grupo: desde 1.150€.\nVuelo: 600-700€.",
        cta: { text: "Ver viajes a Vietnam", href: "/destino/vietnam" },
      },
      {
        heading: "4. Perú — Historia, aventura y ceviche",
        body: "Machu Picchu justifica el viaje por sí solo, pero Perú es mucho más: Cusco, el Valle Sagrado, Lima gastronómica... Y los precios locales son muy asequibles una vez allí.\n\nPrecio medio viaje en grupo: desde 1.390€.\nVuelo: 750-900€.",
        cta: { text: "Ver viajes a Perú", href: "/destino/peru" },
      },
      {
        heading: "5. Bali — Espiritualidad tropical sin arruinarte",
        body: "Indonesia es uno de los países más baratos del sudeste asiático. En Bali puedes comer por 2-4€, alojarte en un hotel con piscina por 25€ y subir un volcán al amanecer por 15€.\n\nPrecio medio viaje en grupo: desde 1.250€.\nVuelo: 650-800€.",
        cta: { text: "Ver viajes a Bali", href: "/destino/bali" },
      },
      {
        heading: "El truco: viajar en grupo para ahorrar más",
        body: "Cuando viajas en grupo organizado, los precios bajan porque se negocia en bloque: alojamiento, transporte, actividades... Todo sale más barato que si lo organizas por tu cuenta. Y encima, no pierdes tiempo planificando.\n\nSi tu freno es el dinero, calcula: un viaje de 12 días a Tailandia por 1.090€ + 600€ de vuelo = 1.690€ todo incluido. Son 140€ por día con alojamiento, transporte, actividades y coordinador. ¿Cuánto gastarías por tu cuenta?",
        cta: { text: "Ver todos los viajes y precios", href: "/viajes#resultados" },
      },
    ],
  },
  {
    slug: "que-incluye-viaje-grupo",
    title: "¿Qué incluye realmente un viaje en grupo organizado?",
    excerpt: "Alojamiento, transporte, actividades, coordinador... desglosamos todo lo que está incluido para que no haya sorpresas.",
    metaDescription: "¿Qué incluye un viaje en grupo organizado? Desglose completo: alojamiento, transporte, actividades y coordinador. Sin sorpresas ni letra pequeña.",
    category: "Guías",
    image: "/images/hero-maldivas.jpg",
    imageAlt: "Viajeros en grupo disfrutando de un bungalow en Maldivas con todo incluido",
    date: "15 Feb 2026",
    dateISO: "2026-02-15",
    readTime: "5 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["maldivas", "japon", "costa-rica"],
    relatedSlugs: ["destinos-baratos-jovenes", "preparar-maleta-viaje-aventura"],
    tags: ["viaje en grupo", "qué incluye", "viajes organizados", "precio viaje grupo", "todo incluido"],
    sections: [
      {
        heading: "La pregunta del millón: ¿qué entra y qué no?",
        body: "Cuando ves \"desde 1.090€\" te preguntas qué hay detrás de esa cifra. Es normal. La transparencia es clave para tomar buenas decisiones. Aquí te lo explicamos todo, sin letra pequeña.",
      },
      {
        heading: "Lo que SÍ incluye tu viaje con Travelhood",
        body: "• Alojamiento completo — Hoteles, hostels boutique o alojamientos únicos según el destino. Siempre con buena valoración y ubicación estratégica.\n\n• Transporte interno — Traslados entre ciudades, aeropuertos, actividades. En furgoneta privada, tren, barca... según el destino.\n\n• Actividades y experiencias — Las experiencias clave del itinerario están incluidas. No vas a un destino para quedarte en el hotel.\n\n• Coordinador Travelhood — Una persona de nuestro equipo viaja contigo. No es un guía turístico que te suelta una chapa. Es alguien que gestiona, resuelve y hace que el grupo funcione.\n\n• Extras según destino — Japan Rail Pass en Japón, noche en jaima en el desierto de Marruecos, crucero por el Nilo en Egipto...",
      },
      {
        heading: "Lo que NO incluye (y por qué)",
        body: "• Vuelo internacional — Cada viajero sale de una ciudad diferente, así que dejamos que tú reserves tu vuelo para encontrar la mejor oferta desde tu aeropuerto.\n\n• Comidas no especificadas — Algunas comidas están incluidas (especialmente desayunos), pero dejamos otras libres para que explores la gastronomía local a tu ritmo.\n\n• Gastos personales — Souvenirs, propinas, excursiones opcionales extra.",
      },
      {
        heading: "¿Sale más barato que hacerlo por tu cuenta?",
        body: "En el 90% de los casos, sí. El precio de grupo en hoteles y actividades es significativamente menor. Además, ahorras tiempo de planificación (que tiene un valor enorme) y evitas errores de logística que pueden costarte dinero.\n\nEjemplo real: un viaje de 12 días a Tailandia por tu cuenta te costaría unos 1.400-1.800€ en alojamiento + transporte + actividades. Con nosotros, desde 1.090€. Y con coordinador incluido.",
        cta: { text: "Comparar viajes y precios", href: "/viajes#resultados" },
      },
    ],
  },
  {
    slug: "como-hacer-amigos-viajando",
    title: "Cómo hacer amigos viajando: de desconocidos a familia en 10 días",
    excerpt: "El secreto de los viajes en grupo no es el destino: es la gente. Así es como se forjan amistades que duran toda la vida.",
    metaDescription: "Descubre cómo los viajes en grupo crean amistades reales que duran más allá del viaje. Historias y consejos de viajeros de 20 a 35 años.",
    category: "Comunidad",
    image: "/images/hero-laponia.jpg",
    imageAlt: "Grupo de amigos viajeros viendo auroras boreales juntos en Laponia",
    date: "8 Feb 2026",
    dateISO: "2026-02-08",
    readTime: "7 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["laponia", "brasil", "japon"],
    relatedSlugs: ["viajar-sola-sin-miedo", "por-que-viajar-en-grupo"],
    tags: ["hacer amigos viajando", "viajes en grupo", "comunidad viajera", "amigos de viaje"],
    sections: [
      {
        heading: "El ingrediente secreto de los viajes en grupo",
        body: "Hay algo que pasa cuando compartes experiencias intensas con desconocidos: dejan de ser desconocidos muy rápido. Un volcán al amanecer, una noche en el desierto, un tuk-tuk compartido bajo la lluvia tropical... Esas cosas crean lazos que un after work nunca conseguirá.\n\nNo es magia. Es psicología. Las experiencias compartidas fuera de la zona de confort generan conexiones más profundas que meses de contacto casual.",
      },
      {
        heading: "Día 1: Desconocidos. Día 3: Inseparables",
        body: "El patrón se repite en cada viaje. El primer día hay nervios, miradas tímidas, conversaciones educadas. El segundo día ya hay bromas internas. El tercero, nadie quiere separarse del grupo.\n\nPablo, 25 años, Barcelona: \"Ver las auroras boreales con 13 personas más que sienten lo mismo que tú... no hay palabras.\"\n\nAna, 31 años, Valencia: \"Japón me volaba la cabeza cada día. Y el grupo hizo que fuera 10 veces mejor.\"",
        image: "/images/hero-laponia.jpg",
        imageAlt: "Viajeros jóvenes compartiendo experiencias en grupo en Laponia",
      },
      {
        heading: "Por qué funciona (y por qué no pasa en un hotel all-inclusive)",
        body: "La diferencia está en la estructura. Un viaje en grupo con Travelhood está diseñado para que la conexión ocurra naturalmente:\n\n• Grupo reducido (12-18 personas) — Lo suficientemente grande para variedad, lo suficientemente pequeño para intimidad.\n\n• Misma franja de edad (20-35) — Afinidad natural. Mismas referencias, mismos intereses, misma energía.\n\n• Experiencias compartidas — No estáis sentados en tumbonas mirando el móvil. Estáis subiendo volcanes, cenando en mercados locales y perdiéndoos por ciudades desconocidas.\n\n• Coordinador que facilita — Alguien que rompe el hielo, organiza dinámicas naturales y se asegura de que nadie se quede atrás.",
      },
      {
        heading: "Después del viaje: ¿se mantiene la relación?",
        body: "Esta es la pregunta más importante. Y la respuesta es: sí, pero depende.\n\nLo que hemos visto en más de 500 viajeros: el 80% mantiene el grupo de WhatsApp activo meses después. El 60% queda al menos una vez al volver. El 35% planifica otro viaje juntos.\n\nDavid, 30 años, Málaga: \"Repetí con Travelhood. La primera vez fui solo, la segunda convencí a dos amigos.\"",
        cta: { text: "Únete a la próxima aventura", href: "/viajes#resultados" },
      },
    ],
  },
  {
    slug: "preparar-maleta-viaje-aventura",
    title: "Cómo preparar la maleta para un viaje de aventura sin morir en el intento",
    excerpt: "La lista definitiva de lo que necesitas (y lo que no) para un viaje en grupo de 10-15 días con destino aventura.",
    metaDescription: "Lista completa para preparar la maleta de un viaje de aventura de 10-15 días. Qué llevar, qué no llevar y trucos de viajeros expertos.",
    category: "Guías",
    image: "/images/hero-japon.jpg",
    imageAlt: "Mochila preparada para un viaje de aventura con vistas a montañas de Japón",
    date: "1 Feb 2026",
    dateISO: "2026-02-01",
    readTime: "5 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["japon", "islandia", "costa-rica"],
    relatedSlugs: ["que-incluye-viaje-grupo", "destinos-baratos-jovenes"],
    tags: ["preparar maleta", "lista equipaje viaje", "mochila viaje aventura", "qué llevar viaje grupo"],
    sections: [
      {
        heading: "La regla de oro: menos es más",
        body: "El error número uno de cualquier viajero novato es llevar demasiado. Vas a cargar con esa maleta por aeropuertos, trenes, tuk-tuks y calles empedradas. Cada kilo cuenta.\n\nRegla práctica: si dudas si llevar algo, no lo lleves. En el 90% de los casos no lo vas a necesitar, y si lo necesitas, lo compras allí (probablemente más barato).",
      },
      {
        heading: "Maleta vs. mochila: ¿cuál elegir?",
        body: "Para viajes de aventura, la respuesta casi siempre es mochila. Elige una de 40-50 litros con apertura tipo maleta (no solo por arriba). Las ruedas no funcionan en arrozales de Bali ni en las medinas de Marruecos.\n\nSi vas a un destino más urbano (Japón, Grecia), puedes llevar una maleta de cabina rígida. Pero asegúrate de que puedes moverla con una mano.",
      },
      {
        heading: "Lo imprescindible (lo que SÍ llevar)",
        body: "• Ropa técnica que seque rápido — 3-4 camisetas, 2 pantalones largos convertibles, 1 forro polar.\n\n• Calzado — Unas zapatillas de trekking cómodas (ya usadas, nunca estrenar) y unas chanclas.\n\n• Botiquín básico — Ibuprofeno, antidiarreico, tiritas, protector solar SPF50.\n\n• Electrónica — Móvil, cargador, adaptador universal, batería externa.\n\n• Documentación — Pasaporte (con 6 meses de validez), copia digital en el móvil, tarjeta sanitaria europea si aplica.\n\n• Una sudadera o chaqueta fina — Para aviones, noches frescas o aire acondicionado extremo asiático.",
      },
      {
        heading: "Lo que NO necesitas (ahorra espacio)",
        body: "• Secador de pelo — Los alojamientos suelen tener.\n• Toalla grande — Lleva una de microfibra si acaso.\n• Más de 2 pares de zapatos — No vas a una boda.\n• Libros físicos — Kindle o el móvil.\n• Exceso de \"por si acasos\" — No vas a necesitar 5 camisetas de repuesto.",
        cta: { text: "Ver destinos y preparar tu viaje", href: "/viajes#resultados" },
      },
    ],
  },
  {
    slug: "por-que-viajar-en-grupo",
    title: "5 razones por las que viajar en grupo cambia tu forma de ver el mundo",
    excerpt: "Más allá de la comodidad: seguridad, precio, conexiones reales y experiencias que no vivirías viajando por tu cuenta.",
    metaDescription: "5 razones para viajar en grupo en 2026: seguridad, ahorro, amistades reales y experiencias únicas. Por qué cada vez más jóvenes eligen viajes en grupo organizados.",
    category: "Inspiración",
    image: "/images/hero-main.jpg",
    imageAlt: "Grupo de jóvenes viajeros celebrando juntos una experiencia de viaje",
    date: "25 Ene 2026",
    dateISO: "2026-01-25",
    readTime: "6 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["brasil", "maldivas", "laponia"],
    relatedSlugs: ["viajar-sola-sin-miedo", "como-hacer-amigos-viajando"],
    tags: ["viajar en grupo", "ventajas viaje grupo", "viajes organizados jóvenes", "por qué viajar en grupo"],
    sections: [
      {
        heading: "Viajar en grupo no es lo que piensas",
        body: "Cuando escuchas \"viaje en grupo\" probablemente piensas en un autobús con 50 jubilados siguiendo un paraguas. Olvida eso.\n\nLos viajes en grupo para jóvenes de 20-35 años son algo completamente diferente: grupos reducidos, itinerarios de aventura, libertad dentro de una estructura y personas con las mismas ganas de vivir.",
      },
      {
        heading: "1. Seguridad sin sacrificar aventura",
        body: "Viajar a países como Vietnam, Marruecos o Perú con un grupo y un coordinador es un nivel de seguridad que no tienes viajando solo. Pero no es seguridad aburrida: es tener a alguien que conoce el terreno, que habla con los locales y que resuelve cualquier imprevisto.\n\nEl resultado: puedes vivir experiencias más intensas porque tienes un respaldo real.",
      },
      {
        heading: "2. Precio: el grupo abarata todo",
        body: "Hoteles, transportes, actividades, guías locales... todo se negocia a precio de grupo. En muchos destinos, un viaje organizado sale más barato que hacerlo por tu cuenta (y sin el estrés de planificarlo).\n\nEjemplo: un Safari en Zanzíbar que por libre cuesta 200€/persona, en grupo baja a 80€.",
      },
      {
        heading: "3. Amistades reales, no seguidores",
        body: "La gente que conoces viajando comparte algo contigo que tus amigos de siempre no: una experiencia que os cambió a todos. Subir un volcán juntos, cenar en un mercado nocturno, perderse por una medina... eso crea lazos diferentes.\n\nMiguel, 27, Sevilla: \"Pensé que Maldivas en grupo sería raro. Fue la mejor decisión que he tomado.\"",
        image: "/images/hero-maldivas.jpg",
        imageAlt: "Amigos de viaje disfrutando juntos en las Maldivas",
      },
      {
        heading: "4. Experiencias que no vivirías solo",
        body: "Hay experiencias que simplemente no son posibles (o no son lo mismo) viajando solo: una noche en una jaima del Sahara con todo el grupo, un trineo de huskies en Laponia, una cena privada en un riad de Marrakech.\n\nEl grupo abre puertas que el viajero individual no puede abrir.",
      },
      {
        heading: "5. Cero estrés logístico",
        body: "No tienes que reservar hoteles, comparar precios, planificar rutas, buscar restaurantes... Todo eso ya está hecho. Tú solo tienes que decidir ir y hacer la maleta.\n\nEse tiempo que ahorras planificando es tiempo que dedicas a disfrutar. Y créeme, se nota.",
        cta: { text: "Descubre tu próximo viaje en grupo", href: "/viajes#resultados" },
      },
    ],
  },
  {
    slug: "mejores-destinos-primer-viaje-grupo",
    title: "Los 10 mejores destinos para tu primer viaje en grupo",
    excerpt: "¿Primera vez viajando en grupo? Estos son los destinos donde la experiencia es inmejorable para debutantes.",
    metaDescription: "Los 10 mejores destinos para tu primer viaje en grupo en 2026. Guía completa con precios, lo que incluye y por qué cada destino es perfecto para empezar.",
    category: "Destinos",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Grupo de jóvenes viajeros en su primer viaje en grupo",
    date: "3 Mar 2026",
    dateISO: "2026-03-03",
    readTime: "8 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "marruecos", "grecia", "bali", "costa-rica"],
    relatedSlugs: ["destinos-baratos-jovenes", "como-elegir-primer-viaje-grupo"],
    tags: ["primer viaje en grupo", "mejores destinos", "viajes para principiantes", "viajes jóvenes 2026"],
    sections: [
      { heading: "¿Por qué importa elegir bien el primer destino?", body: "Tu primer viaje en grupo marca la diferencia entre enamorarte de esta forma de viajar o no repetir. El destino importa, pero importa más que sea accesible, seguro y con el equilibrio justo de aventura y comodidad. No necesitas empezar con el destino más exótico. Necesitas empezar con el que te haga decir: 'Quiero repetir esto'.\n\nHemos analizado más de 500 viajeros que debutaron con Travelhood y estos son los 10 destinos que más repiten los que vinieron solos por primera vez." },
      { heading: "1. Tailandia — El debut perfecto", body: "Tailandia es el destino favorito para debutar en viajes en grupo. ¿Por qué? Porque lo tiene todo: templos espectaculares, playas de película, la mejor comida callejera del mundo y precios imbatibles. Es seguro, la gente es amabilísima y el choque cultural es justo: lo suficiente para sentir que estás lejos, pero no tanto como para sentirte perdido.\n\nEl grupo funciona especialmente bien aquí porque las experiencias son muy variadas: un día estás visitando templos en Chiang Mai y al siguiente haciendo snorkel en Phi Phi. Desde 1.090€.", cta: { text: "Ver viajes a Tailandia", href: "/destino/tailandia" } },
      { heading: "2. Marruecos — Exótico y cercano", body: "A solo 2 horas de vuelo y desde 590€, Marruecos es la puerta de entrada perfecta al viaje en grupo. El desierto del Sahara bajo las estrellas, las medinas de Marrakech y Fez, la ciudad azul de Chefchaouen... Es un destino intenso pero accesible, perfecto para quienes quieren algo diferente sin irse al otro lado del mundo.\n\nLos puentes (mayo, octubre) son ideales para una primera experiencia de 5 días que te deja con ganas de más.", cta: { text: "Ver viajes a Marruecos", href: "/destino/marruecos" } },
      { heading: "3-5. Grecia, Bali y Costa Rica", body: "Grecia es Europa en su máxima expresión: islas de postal, atardeceres en Santorini y gastronomía mediterránea. Perfecto para quienes quieren un destino cercano y relajado. Desde 790€.\n\nBali ofrece una experiencia transformadora: arrozales, volcanes al amanecer, templos y playas. Es espiritualidad + aventura en un paquete tropical. Desde 1.250€.\n\nCosta Rica es biodiversidad extrema: volcanes, selvas, playas del Caribe y del Pacífico. Pura vida no es solo un eslogan, es la actitud del país. Desde 1.390€.", cta: { text: "Ver todos los destinos", href: "/viajes#resultados" } },
      { heading: "6-10. Japón, Perú, Egipto, Vietnam y Colombia", body: "Japón es el viaje que cambia tu perspectiva. Más complejo culturalmente, pero con coordinador se convierte en una experiencia fluida e inolvidable.\n\nPerú combina historia (Machu Picchu), gastronomía de talla mundial y naturaleza andina.\n\nEgipto es 5.000 años de historia en un viaje con pirámides, crucero por el Nilo y templos faraónicos.\n\nVietnam ofrece la mejor relación calidad-precio de Asia con paisajes espectaculares.\n\nColombia es el destino emergente: Caribe, montañas cafeteras y la mejor hospitalidad de Sudamérica." },
    ],
  },
  {
    slug: "viajes-grupo-vs-viajar-solo-comparativa",
    title: "Viajes en grupo vs. viajar por tu cuenta: comparativa real",
    excerpt: "¿Es mejor viajar solo o en grupo organizado? Analizamos precio, seguridad, experiencia y conexiones con datos reales.",
    metaDescription: "Comparativa real entre viajar solo y viajes en grupo organizados para jóvenes en 2026. Precio, seguridad, experiencia y amistades analizados.",
    category: "Guías",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Comparativa visual entre viajar solo y en grupo",
    date: "2 Mar 2026",
    dateISO: "2026-03-02",
    readTime: "7 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "japon"],
    relatedSlugs: ["por-que-viajar-en-grupo", "que-incluye-viaje-grupo"],
    tags: ["viajes en grupo vs solo", "comparativa viajes", "ventajas viaje grupo", "viajar solo"],
    sections: [
      { heading: "La eterna pregunta: ¿solo o en grupo?", body: "Es la pregunta que se hace todo viajero joven: ¿debería organizar todo por mi cuenta o unirme a un grupo? No hay una respuesta universal, pero sí datos objetivos que te ayudarán a decidir. En esta comparativa analizamos precio, seguridad, experiencia social y logística para que elijas con información real, no con prejuicios." },
      { heading: "Precio: ¿dónde sale más barato?", body: "Viajar solo puede ser más barato si eres muy hábil planificando y estás dispuesto a alojarte en dormitorios compartidos de hostel. Pero en la práctica, el viaje en grupo sale igual o más barato porque los precios se negocian en bloque.\n\nEjemplo real con Tailandia 12 días:\n- Solo: 1.400-1.800€ (alojamiento + transporte + actividades)\n- Grupo Travelhood: desde 1.090€ (todo incluido excepto vuelo)\n\nY el grupo incluye coordinador, experiencias que por tu cuenta no accederías y cero tiempo perdido planificando.", cta: { text: "Ver viajes y precios", href: "/viajes#resultados" } },
      { heading: "Seguridad: ¿quién gana?", body: "Aquí no hay debate. Viajar con grupo y coordinador es objetivamente más seguro que hacerlo solo, especialmente en destinos como Vietnam, Marruecos o Perú. No es que sean peligrosos, pero tener a alguien que conoce el terreno, habla con los locales y resuelve imprevistos cambia la experiencia.\n\nEl 100% de nuestros viajes se han completado sin incidentes graves. Con coordinador 24h, seguro incluido y protocolos de seguridad." },
      { heading: "Experiencia social: el factor diferencial", body: "Aquí es donde el grupo gana por goleada. Viajar solo es liberador pero puede ser solitario. Un grupo de 14 personas de tu misma edad (20-35 años) que comparten experiencias intensas crea lazos que duran años.\n\nDatos reales de Travelhood: el 70% de viajeros vienen solos. El 80% mantiene el grupo de WhatsApp activo meses después. El 35% planifica otro viaje juntos. El 98% repetirían.", cta: { text: "Leer más sobre viajar sola", href: "/viajar-sola" } },
    ],
  },
  {
    slug: "cuanto-cuesta-viaje-grupo-presupuesto",
    title: "¿Cuánto cuesta un viaje en grupo? Presupuesto real 2026",
    excerpt: "Desglose completo de costes: viaje, vuelo, gastos en destino. Con ejemplos reales de presupuestos por destino.",
    metaDescription: "¿Cuánto cuesta un viaje en grupo para jóvenes en 2026? Presupuesto real desglosado: viaje desde 590€ + vuelo + gastos en destino. Ejemplos por país.",
    category: "Guías",
    image: "/images/hero-japon.jpg",
    imageAlt: "Calculadora de presupuesto de viaje con monedas internacionales",
    date: "27 Feb 2026",
    dateISO: "2026-02-27",
    readTime: "6 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["marruecos", "tailandia", "vietnam", "japon"],
    relatedSlugs: ["que-incluye-viaje-grupo", "destinos-baratos-jovenes"],
    tags: ["presupuesto viaje grupo", "cuánto cuesta viajar", "viajes baratos", "presupuesto 2026"],
    sections: [
      { heading: "La pregunta que todos nos hacemos", body: "\"¿Cuánto me va a costar?\" es la primera pregunta cuando piensas en un viaje. Y mereces una respuesta clara, sin letra pequeña. En Travelhood creemos en la transparencia total: aquí tienes el desglose completo para que sepas exactamente qué vas a pagar.\n\nLos viajes cuestan entre 590€ y 1.590€, sin vuelo. Cada viaje incluye coordinador, alojamiento, transporte interno y seguro." },
      { heading: "Desglose: viaje + vuelo + gastos", body: "Tu presupuesto total tiene tres partes:\n\n1. Precio del viaje con Travelhood (590-1.590€): incluye alojamiento, transporte interno, actividades, coordinador y seguro.\n\n2. Vuelo internacional (50-900€): varía mucho según destino. Marruecos desde 50€, Tailandia 500-700€, Japón 700-900€.\n\n3. Gastos en destino (200-500€ para 10-14 días): comidas no incluidas, souvenirs, propinas, actividades extra opcionales." },
      { heading: "Ejemplos reales por destino", body: "Marruecos (puente 5 días): 590€ viaje + 100€ vuelo + 150€ gastos = ~840€ total.\n\nTailandia (12 días): 1.090€ viaje + 600€ vuelo + 300€ gastos = ~1.990€ total.\n\nJapón (14 días): 1.490€ viaje + 800€ vuelo + 400€ gastos = ~2.690€ total.\n\nGrecia (10 días): 990€ viaje + 200€ vuelo + 250€ gastos = ~1.440€ total.\n\nVietnam (14 días): 1.150€ viaje + 650€ vuelo + 200€ gastos = ~2.000€ total.", cta: { text: "Ver todos los precios", href: "/viajes#resultados" } },
      { heading: "Trucos para ahorrar más", body: "1. Reserva con antelación: tanto el viaje (early bird con descuento) como el vuelo (3-4 meses antes es el sweet spot).\n\n2. Viaja en temporada media: septiembre y mayo suelen tener los mejores precios.\n\n3. Aprovecha puentes: Marruecos en puente es la opción más barata del catálogo.\n\n4. Come local: en Asia puedes comer espectacular por 2-5€. No necesitas restaurantes turísticos.\n\n5. Mira ofertas: nuestra página de ofertas tiene las últimas plazas con descuento.", cta: { text: "Ver ofertas actuales", href: "/ofertas" } },
    ],
  },
  {
    slug: "destinos-semana-santa-grupo",
    title: "Mejores destinos para Semana Santa en grupo",
    excerpt: "5 destinos perfectos para aprovechar Semana Santa 2026 viajando en grupo. Fechas, precios y por qué cada uno merece la pena.",
    metaDescription: "Los mejores destinos para viajar en grupo en Semana Santa 2026: Japón, Tailandia, Bali, Marruecos y Egipto. Precios, fechas y plazas disponibles.",
    category: "Destinos",
    image: "/images/hero-japon.jpg",
    imageAlt: "Cerezos en flor en Japón durante Semana Santa",
    date: "25 Feb 2026",
    dateISO: "2026-02-25",
    readTime: "7 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["japon", "tailandia", "bali", "marruecos", "egipto"],
    relatedSlugs: ["mejores-destinos-primer-viaje-grupo", "cuanto-cuesta-viaje-grupo-presupuesto"],
    tags: ["semana santa 2026", "viajes semana santa", "destinos semana santa", "viajes grupo semana santa"],
    sections: [
      { heading: "Semana Santa 2026: el primer gran viaje del año", body: "Semana Santa 2026 cae del 28 de marzo al 6 de abril, y es la primera oportunidad real para un viaje largo. En Travelhood tenemos 5 destinos preparados con fechas, coordinador y plazas limitadas. Si estás leyendo esto, es el momento de decidirte: las plazas de Semana Santa se agotan rápido." },
      { heading: "Japón — Cerezos en flor (14 días, desde 1.390€)", body: "Semana Santa coincide con la temporada de cerezos en flor en Japón. Es probablemente el momento más mágico para visitar el país: Tokio, Kioto, Osaka y Nara envueltos en flores rosas. 14 días con Japan Rail Pass incluido, coordinador y alojamiento.\n\nEs el viaje más demandado de Semana Santa. Quedan pocas plazas.", cta: { text: "Ver viaje a Japón", href: "/destino/japon" } },
      { heading: "Tailandia y Bali — Asia tropical", body: "Tailandia en Semana Santa (12 días, desde 1.090€ con promo early bird) es una apuesta segura: buen tiempo, templos, playas y street food. Es el destino más versátil y uno de los más económicos.\n\nBali (13 días, desde 1.250€) ofrece una experiencia más espiritual: arrozales, volcanes al amanecer, templos hindúes y playas de Nusa Penida.\n\nAmbos están en su mejor momento climático en estas fechas.", cta: { text: "Ver viajes a Asia", href: "/destinos/asia" } },
      { heading: "Marruecos y Egipto — Cercanos e intensos", body: "Marruecos (9 días, desde 790€ con early bird) es intenso, cercano y económico. Desierto, medinas, Atlas y la ciudad azul de Chefchaouen. Vuelos desde 100€.\n\nEgipto (10 días, desde 990€ con oferta flash) es 5.000 años de historia: Pirámides, crucero por el Nilo, templos de Luxor. A 4 horas de vuelo.\n\nSi buscas impacto cultural máximo con presupuesto contenido, estos dos son tu mejor opción.", cta: { text: "Ver viajes a África", href: "/destinos/africa" } },
    ],
  },
  {
    slug: "viajes-aventura-jovenes-repiten",
    title: "Viajes de aventura para jóvenes: los que más repiten",
    excerpt: "¿Qué destinos de aventura tienen más tasa de repetición? Los datos hablan: estos son los que enganchan.",
    metaDescription: "Los viajes de aventura en grupo para jóvenes que más repiten en 2026. Ranking de destinos por tasa de repetición con datos reales de Travelhood.",
    category: "Inspiración",
    image: "/images/hero-laponia.jpg",
    imageAlt: "Jóvenes viajeros en una aventura en grupo",
    date: "20 Feb 2026",
    dateISO: "2026-02-20",
    readTime: "6 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["costa-rica", "islandia", "peru", "marruecos"],
    relatedSlugs: ["mejores-destinos-primer-viaje-grupo", "por-que-viajar-en-grupo"],
    tags: ["viajes aventura", "viajes jóvenes", "aventura en grupo", "destinos aventura 2026"],
    sections: [
      { heading: "La aventura que te hace volver", body: "Hay viajes que disfrutas. Y hay viajes que te cambian. Los viajes de aventura pertenecen a la segunda categoría: trekkings al amanecer, desiertos bajo las estrellas, volcanes que te dejan sin aliento. Son los viajes que más enganchan y los que generan más tasa de repetición entre nuestros viajeros." },
      { heading: "Costa Rica — La aventura más completa", body: "Costa Rica lidera nuestra tasa de repetición de aventura. Volcanes activos, selvas con biodiversidad extrema, playas del Caribe y del Pacífico. Todo en 12 días. La variedad de experiencias es difícil de superar: tirolinas sobre el bosque nuboso, kayak entre manglares, avistamiento de perezosos y tortugas.\n\nDesde 1.390€ con todo incluido.", cta: { text: "Ver viajes a Costa Rica", href: "/destino/costa-rica" } },
      { heading: "Islandia — Paisajes de otro planeta", body: "Islandia es el destino que más sorprende a los debutantes. Géiseres, cascadas imposibles, glaciares, aguas termales y (en octubre) auroras boreales. Es naturaleza en estado puro en un formato compacto de 6 días, perfecto para puentes.\n\nDesde 890€ con reserva anticipada.", cta: { text: "Ver viajes a Islandia", href: "/destino/islandia" } },
      { heading: "Perú y Marruecos — Historia + aventura", body: "Perú combina aventura con historia como ningún otro destino: Machu Picchu al amanecer, trekking por el Valle Sagrado y aclimatación en Cusco. 14 días que te cambian.\n\nMarruecos ofrece aventura accesible: trekking en el Atlas, noche en jaima en el Sahara, surfear en Essaouira. Y todo a 2 horas de vuelo. El puente más aventurero que existe.", cta: { text: "Ver viajes de aventura", href: "/tipos/aventura" } },
    ],
  },
  {
    slug: "que-hacer-no-conoces-nadie-viaje-grupo",
    title: "Qué hacer si no conoces a nadie en un viaje en grupo",
    excerpt: "El 70% de los viajeros de Travelhood llegan solos. Así es como el grupo se forma y las amistades surgen naturalmente.",
    metaDescription: "¿Vas solo a un viaje en grupo? El 70% de viajeros de Travelhood también. Guía práctica para integrarte, hacer amigos y disfrutar al máximo.",
    category: "Comunidad",
    image: "/images/hero-maldivas.jpg",
    imageAlt: "Grupo de viajeros jóvenes conociéndose por primera vez",
    date: "18 Feb 2026",
    dateISO: "2026-02-18",
    readTime: "5 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["brasil", "laponia"],
    relatedSlugs: ["como-hacer-amigos-viajando", "viajar-sola-sin-miedo"],
    tags: ["no conocer a nadie viaje", "viaje en grupo solo", "hacer amigos viajando", "integración grupo"],
    sections: [
      { heading: "El miedo es normal. Y es temporal.", body: "Subir a un avión sin conocer a nadie del grupo genera nervios. Es humano. Pero ese miedo tiene fecha de caducidad: unas 24 horas. Lo hemos visto en más de 500 viajeros. El primer día hay miradas tímidas. El segundo, bromas internas. El tercero, planes improvisados del grupo.\n\nEl 70% de los viajeros de Travelhood reservan solos. No eres la excepción. Eres la norma." },
      { heading: "Cómo funciona la integración", body: "No dejamos la integración al azar. Nuestro proceso tiene tres fases:\n\n1. Antes del viaje: te añadimos al grupo de WhatsApp 2-3 semanas antes. Os presentáis, compartís expectativas y empezáis a generar vínculo.\n\n2. El primer día: el coordinador organiza una cena de bienvenida con dinámicas naturales (nada forzado). Para cuando termina la cena, ya hay subgrupos formándose.\n\n3. Los días siguientes: las experiencias compartidas hacen el resto. Subir un volcán juntos, perderse por una medina, compartir un atardecer... Eso crea lazos más fuertes que meses de contacto casual." },
      { heading: "Consejos prácticos de viajeros repetidores", body: "1. Sé tú mismo/a. No intentes ser quien no eres. Los grupos de Travelhood valoran la autenticidad.\n\n2. Habla primero. No esperes a que te hablen. Un simple \"¿De dónde eres?\" abre conversaciones.\n\n3. Comparte experiencias. Ofrece compartir taxi al aeropuerto, recomendar un sitio que has visto, proponer un plan en el tiempo libre.\n\n4. No te aísles. Si un día estás cansado, está bien descansar. Pero no te aísles varios días seguidos.\n\n5. Disfruta del proceso. Las mejores amistades de viaje surgen de momentos inesperados, no de esfuerzos planificados." },
      { heading: "Lo que dicen los que ya fueron solos", body: "Laura, 28, Madrid: \"Fui sin conocer a nadie. Volví con gente que ya considero amigos.\"\n\nPablo, 25, Barcelona: \"Ver las auroras boreales con 13 personas más que sienten lo mismo que tú... no hay palabras.\"\n\nDavid, 30, Málaga: \"Repetí con Travelhood. La primera vez fui solo, la segunda convencí a dos amigos.\"", cta: { text: "Lánzate a tu primer viaje", href: "/viajes#resultados" } },
    ],
  },
  {
    slug: "guia-marruecos-jovenes",
    title: "Guía de Marruecos para jóvenes: todo lo que necesitas",
    excerpt: "Visado, dinero, ropa, seguridad, mejor época... Todo lo que necesitas saber antes de viajar a Marruecos en grupo.",
    metaDescription: "Guía completa de Marruecos para jóvenes 2026: visado, seguridad, dinero, ropa, mejor época y qué ver. Todo para tu viaje en grupo.",
    category: "Guías",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Zocos y medinas de Marruecos para viajeros jóvenes",
    date: "12 Feb 2026",
    dateISO: "2026-02-12",
    readTime: "8 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["marruecos", "egipto"],
    relatedSlugs: ["destinos-baratos-jovenes", "preparar-maleta-viaje-aventura"],
    tags: ["guía marruecos", "marruecos jóvenes", "viajar a marruecos", "marruecos 2026"],
    sections: [
      { heading: "Marruecos: el destino que te sorprende", body: "Marruecos está a 2 horas de vuelo desde España y parece otro mundo. Medinas laberínticas, desierto infinito, montañas del Atlas, ciudades azules y una gastronomía que enamora. Es uno de nuestros destinos más populares por su combinación de exotismo, cercanía y precio accesible.\n\nEsta guía te prepara para que llegues sabiendo todo lo necesario." },
      { heading: "Documentación, visado y dinero", body: "Visado: los ciudadanos españoles no necesitan visado para estancias de hasta 90 días.\n\nMoneda: el dírham marroquí (MAD). 1€ ≈ 11 MAD. Se puede cambiar en el aeropuerto o cajeros. Las tarjetas funcionan en hoteles y restaurantes turísticos, pero lleva efectivo para los zocos.\n\nSeguro: incluido con el viaje de Travelhood. Si vas por tu cuenta, contrata uno con cobertura médica." },
      { heading: "Qué llevar y qué no", body: "Ropa cómoda y ligera de día, algo de abrigo para las noches en el desierto y montañas (puede bajar a 5°C). Zapatos cómodos para caminar por medinas empedradas. Bañador para riads con piscina y hammams.\n\nEvita ropa excesivamente corta o escotada fuera de zonas turísticas por respeto cultural. Un pañuelo grande es versátil: cubre cabeza del sol, sirve de manta y protege del polvo del desierto.\n\nProtector solar alto y gafas de sol imprescindibles.", cta: { text: "Lista completa de maleta", href: "/blog/preparar-maleta-viaje-aventura" } },
      { heading: "Seguridad y consejos prácticos", body: "Marruecos es seguro para turistas. Las zonas que visitamos (Marrakech, Fez, Sahara, Chefchaouen) están muy acostumbradas al turismo. Con coordinador y grupo, cero preocupaciones.\n\nConsejos: negocia siempre en los zocos (pide un 40-50% menos del precio inicial), cuidado con los falsos guías que se ofrecen en medinas, bebe solo agua embotellada y relájate: la hospitalidad marroquí es genuina.", cta: { text: "Ver viajes a Marruecos", href: "/destino/marruecos" } },
    ],
  },
  {
    slug: "guia-japon-jovenes",
    title: "Guía de Japón para jóvenes: todo lo que necesitas",
    excerpt: "Japan Rail Pass, dinero, costumbres, mejor época, comida... La guía definitiva para tu primer viaje a Japón en grupo.",
    metaDescription: "Guía completa de Japón para jóvenes 2026: Japan Rail Pass, visado, dinero, costumbres, mejor época y qué ver. Todo para tu viaje en grupo.",
    category: "Guías",
    image: "/images/hero-japon.jpg",
    imageAlt: "Templo japonés con cerezos en flor",
    date: "10 Feb 2026",
    dateISO: "2026-02-10",
    readTime: "9 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["japon", "tailandia"],
    relatedSlugs: ["mejores-destinos-primer-viaje-grupo", "cuanto-cuesta-viaje-grupo-presupuesto"],
    tags: ["guía japón", "japón jóvenes", "viajar a japón", "japón 2026", "japan rail pass"],
    sections: [
      { heading: "Japón: el viaje que te cambia la perspectiva", body: "Japón es el viaje que todo viajero joven debería hacer al menos una vez. La combinación de tradición milenaria con tecnología futurista, la gastronomía más diversa del mundo, los paisajes que van del neón de Tokio a los bambúes de Kioto... Japón no se parece a nada que hayas vivido.\n\nCon Travelhood, Japón deja de ser complicado. El coordinador gestiona trenes, alojamientos y reservas, y tú solo te preocupas de disfrutar." },
      { heading: "Documentación, Japan Rail Pass y dinero", body: "Visado: no necesario para españoles (hasta 90 días turista).\n\nJapan Rail Pass: incluido en nuestros viajes. Cubre trenes bala (shinkansen) y líneas locales por todo el país. Es la forma más eficiente de moverse.\n\nDinero: yen japonés (JPY). 1€ ≈ 160 JPY. Japón usa mucho efectivo todavía, especialmente en templos, máquinas expendedoras y restaurantes pequeños. Las tarjetas cada vez se aceptan más, pero lleva yenes.\n\nTarjeta IC (Suica/Pasmo): te la facilitamos. Sirve para metro, konbinis y máquinas." },
      { heading: "Gastronomía: más allá del sushi", body: "Japón tiene la mayor densidad de restaurantes con estrella Michelin del mundo, pero la mejor comida está en la calle y en los restaurantes locales:\n\nRamen: el plato estrella. Cada región tiene su estilo. Desde 6€.\nCurry japonés: comfort food perfecta. Desde 4€.\nOkonomiyaki: tortilla japonesa espectacular en Osaka.\nKonbinis: las tiendas 24h (7-Eleven, Lawson) tienen comida sorprendentemente buena y barata.\nIzakayas: bares de tapas japoneses. La experiencia social definitiva.\n\nComer en Japón es fácil, barato y espectacular.", cta: { text: "Ver viajes a Japón", href: "/destino/japon" } },
      { heading: "Costumbres y etiqueta básica", body: "Japón tiene normas sociales que conviene conocer:\n\n1. Quítate los zapatos al entrar en templos, ryokans y algunas tiendas.\n2. No hables por teléfono en el tren. Es una norma estricta.\n3. No dejes propina. En Japón no se da propina y puede resultar ofensivo.\n4. Recicla bien. Hay 4-5 tipos de basura. Las bolsas de basura son sagradas.\n5. Haz cola. Los japoneses hacen cola para todo. Respétalo.\n6. El onsen (baño termal) se disfruta desnudo. Es una experiencia increíble.\n\nNo te preocupes por las normas: el coordinador te guía en todo." },
    ],
  },
  {
    slug: "guia-tailandia-jovenes",
    title: "Guía de Tailandia para jóvenes: todo lo que necesitas",
    excerpt: "Vacunas, monzón, comida, templos, islas... Todo lo que necesitas saber para tu viaje a Tailandia en grupo.",
    metaDescription: "Guía completa de Tailandia para jóvenes 2026: vacunas, mejor época, comida, templos, islas y presupuesto. Todo para tu viaje en grupo.",
    category: "Guías",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Templos y playas de Tailandia",
    date: "5 Feb 2026",
    dateISO: "2026-02-05",
    readTime: "8 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "bali", "vietnam"],
    relatedSlugs: ["destinos-baratos-jovenes", "guia-japon-jovenes"],
    tags: ["guía tailandia", "tailandia jóvenes", "viajar a tailandia", "tailandia 2026"],
    sections: [
      { heading: "Tailandia: el clásico que nunca falla", body: "Tailandia es el destino favorito de los viajeros jóvenes por una razón: lo tiene absolutamente todo. Templos dorados en Bangkok, montañas con elefantes en Chiang Mai, playas de película en Phi Phi y Krabi, y la mejor comida callejera del mundo por 2-3€. Es seguro, barato, exótico y accesible. El debut perfecto en Asia." },
      { heading: "Documentación, vacunas y salud", body: "Visado: no necesario para españoles (hasta 30 días turista, extensible a 60).\n\nVacunas: no hay obligatorias, pero se recomienda hepatitis A y B, y tétanos. Consulta tu centro de vacunación.\n\nAgua: siempre embotellada, nunca del grifo. Está disponible en todas partes y es muy barata.\n\nMosquitos: usa repelente, especialmente al atardecer. En zonas rurales puede haber dengue (poco frecuente en rutas turísticas).\n\nComida callejera: es segura si el puesto tiene mucha rotación de clientes. Si hay cola, es buena señal." },
      { heading: "Presupuesto en destino", body: "Tailandia es uno de los países más baratos del mundo para turistas:\n\nComida callejera: 1-3€ por plato.\nRestaurante con aire acondicionado: 5-10€.\nCerveza local (Chang, Leo): 1-2€.\nMasaje tailandés: 5-10€ por hora.\nTemplos: 0-5€ entrada.\n\nCon 20-30€ al día en destino vives de lujo. En 12 días, unos 250-350€ de gastos extras.", cta: { text: "Ver presupuesto completo", href: "/blog/cuanto-cuesta-viaje-grupo-presupuesto" } },
      { heading: "Mejor época y monzón", body: "Tailandia tiene tres estaciones: fresca (nov-feb), calurosa (mar-may) y lluviosa (jun-oct). La mejor época es noviembre-febrero: temperaturas agradables y sin lluvias.\n\nPero ojo: la temporada de lluvias no es tan terrible como suena. Llueve fuerte pero corto (1-2 horas), los precios bajan y hay menos turistas. Nuestros viajes de verano (julio) funcionan perfecto.\n\nSemana Santa (marzo) es la transición entre fresca y calurosa: calor pero sin lluvias.", cta: { text: "Ver viajes a Tailandia", href: "/destino/tailandia" } },
    ],
  },
  {
    slug: "guia-bali-jovenes",
    title: "Guía de Bali para jóvenes: todo lo que necesitas",
    excerpt: "Visa on arrival, templos, volcanes, arrozales y playas. La guía definitiva para tu viaje a Bali en grupo.",
    metaDescription: "Guía completa de Bali para jóvenes 2026: visa, mejor época, presupuesto, templos, volcanes y playas. Todo para tu viaje en grupo.",
    category: "Guías",
    image: "/images/hero-maldivas.jpg",
    imageAlt: "Arrozales y templos de Bali",
    date: "3 Feb 2026",
    dateISO: "2026-02-03",
    readTime: "7 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["bali", "tailandia", "sri-lanka"],
    relatedSlugs: ["guia-tailandia-jovenes", "destinos-baratos-jovenes"],
    tags: ["guía bali", "bali jóvenes", "viajar a bali", "bali 2026", "indonesia jóvenes"],
    sections: [
      { heading: "Bali: la isla que conecta cuerpo y alma", body: "Bali es uno de esos lugares que no necesita presentación. Arrozales infinitos en Ubud, volcanes al amanecer, templos hindúes escondidos en la selva, playas de acantilados en Uluwatu y una espiritualidad que impregna cada esquina. Es el destino que buscan quienes quieren algo más que turismo: quieren una experiencia transformadora." },
      { heading: "Documentación y presupuesto", body: "Visa: visa on arrival en el aeropuerto de Bali (35 USD, 30 días). Trámite rápido.\n\nMoneda: rupia indonesia (IDR). 1€ ≈ 17.000 IDR. Los cajeros y casas de cambio están por todas partes.\n\nPresupuesto en destino: Bali es muy barato. Comida local desde 2€, masaje balinés desde 7€, clase de yoga desde 5€, alquiler de moto (no recomendamos sin experiencia) desde 4€/día.\n\nCon 20-25€ al día vives muy bien.", cta: { text: "Ver viajes a Bali", href: "/destino/bali" } },
      { heading: "Qué ver y hacer (más allá de Instagram)", body: "Los arrozales de Tegallalang son icónicos, pero Bali tiene mucho más:\n\nMonte Batur: trekking al volcán al amanecer. 2 horas de subida, vistas infinitas.\nNusa Penida: isla cercana con acantilados brutales y aguas cristalinas.\nUluwatu: atardecer en el templo del acantilado con danza Kecak.\nUbud: mercado, templo del mono, cascadas escondidas y yoga.\nGili Islands: islas sin coches con snorkel y tortugas.\n\nTodo esto está incluido en nuestros itinerarios." },
      { heading: "Mejor época y clima", body: "Bali tiene dos estaciones: seca (abril-octubre) y húmeda (noviembre-marzo). La temporada seca es la mejor para viajar: cielos despejados, temperaturas de 27-30°C y humedad moderada.\n\nNuestros viajes de Semana Santa (marzo-abril) y verano (agosto) coinciden con las mejores condiciones. Septiembre es el mes dorado: clima perfecto y menos turistas que en agosto.", cta: { text: "Ver fechas disponibles", href: "/destino/bali" } },
    ],
  },
  {
    slug: "mejores-viajes-playa-grupo-jovenes",
    title: "Los mejores viajes de playa en grupo para jóvenes",
    excerpt: "Tailandia, Maldivas, Grecia, Bali, Zanzíbar... Los destinos de playa que mejor funcionan en grupo.",
    metaDescription: "Los mejores viajes de playa en grupo para jóvenes de 20-35 años en 2026. Tailandia, Maldivas, Grecia y Bali con coordinador, desde 790€.",
    category: "Destinos",
    image: "/images/hero-maldivas.jpg",
    imageAlt: "Playa paradisíaca para viajes en grupo de jóvenes",
    date: "30 Ene 2026",
    dateISO: "2026-01-30",
    readTime: "6 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["maldivas", "grecia", "tailandia", "bali", "zanzibar"],
    relatedSlugs: ["destinos-baratos-jovenes", "mejores-destinos-primer-viaje-grupo"],
    tags: ["viajes playa grupo", "mejores playas", "viajes playa jóvenes", "playa 2026"],
    sections: [
      { heading: "Playa + grupo = la combinación perfecta", body: "Un viaje de playa en grupo no es un all-inclusive con pulsera. Es explorar las mejores calas, hacer snorkel en arrecifes de coral, cenar en chiringuitos locales y ver atardeceres desde acantilados con gente de tu edad. La playa en grupo se disfruta el doble porque las experiencias se multiplican." },
      { heading: "Tailandia — Playas de película por poco dinero", body: "Las islas del sur de Tailandia (Phi Phi, Krabi, Koh Lanta) tienen algunas de las playas más espectaculares del mundo. Maya Bay, Railay Beach, Four Islands... Y la comida callejera de los puestos de playa es espectacular. Desde 1.090€.\n\nBest for: quienes buscan playas + cultura + gastronomía.", cta: { text: "Ver viajes a Tailandia", href: "/destino/tailandia" } },
      { heading: "Maldivas y Zanzíbar — Paraísos inesperados", body: "Maldivas en grupo suena raro, pero es la mejor forma de disfrutarlo: compartes costes, experiencias y te diviertes mucho más que en un resort solo/a. Guest houses locales en islas habitadas, snorkel con mantas raya y tortugas. Desde 1.350€.\n\nZanzíbar es el secreto mejor guardado: playas de arena blanca, cultura swahili, tour de especias y snorkel en el atolón de Mnemba. Desde 1.190€.", cta: { text: "Ver viajes de playa", href: "/tipos/playa" } },
      { heading: "Grecia y Bali — Los clásicos reinventados", body: "Grecia en barco entre islas es una experiencia incomparable: Santorini al atardecer, Mykonos de noche, calas escondidas de Naxos. Todo por desde 790€ con ferris incluidos.\n\nBali combina playa con espiritualidad: playas de Uluwatu, acantilados de Nusa Penida, puestas de sol que parecen pintadas. Desde 1.250€." },
    ],
  },
  {
    slug: "como-elegir-primer-viaje-grupo",
    title: "Cómo elegir tu primer viaje en grupo (sin equivocarte)",
    excerpt: "Duración, presupuesto, tipo de viaje, temporada... Los criterios clave para acertar en tu primera elección.",
    metaDescription: "Guía para elegir tu primer viaje en grupo en 2026: duración ideal, presupuesto, tipo de viaje y temporada. Acierta sin equivocarte.",
    category: "Guías",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Joven eligiendo su primer viaje en grupo",
    date: "28 Ene 2026",
    dateISO: "2026-01-28",
    readTime: "5 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "marruecos", "grecia"],
    relatedSlugs: ["mejores-destinos-primer-viaje-grupo", "que-incluye-viaje-grupo"],
    tags: ["elegir viaje grupo", "primer viaje grupo", "consejos viaje grupo", "guía elección viaje"],
    sections: [
      { heading: "La decisión más difícil es la primera", body: "Tienes 25 destinos, 6 temporadas y diferentes duraciones. ¿Cómo eliges? La respuesta no es complicada si te haces las preguntas correctas. Esta guía te lleva paso a paso para que tu primera elección sea la acertada." },
      { heading: "Paso 1: ¿Cuántos días tienes?", body: "Tu disponibilidad de vacaciones determina el abanico:\n\n5-6 días (puente): Marruecos, Islandia o Grecia. Escapadas intensas y cercanas.\n\n10-12 días (vacaciones cortas): Tailandia, Egipto, Bali, Costa Rica. La opción más popular.\n\n13-14 días (vacaciones largas): Japón, Perú, Vietnam, México. Inmersiones completas.\n\nSi es tu primer viaje en grupo, recomendamos 10-12 días: suficiente para vivir el destino sin agotarte.", cta: { text: "Ver viajes por duración", href: "/viajes#resultados" } },
      { heading: "Paso 2: ¿Cuál es tu presupuesto?", body: "Sé honesto contigo mismo. El presupuesto total incluye viaje + vuelo + gastos en destino:\n\nHasta 1.000€ total: Marruecos en puente (840€ aprox).\n\nHasta 1.500€ total: Grecia (1.440€ aprox), Marruecos largo.\n\nHasta 2.000€ total: Tailandia (1.990€), Vietnam (2.000€).\n\nHasta 2.500€ total: Bali (2.150€), Costa Rica (2.390€).\n\nMás de 2.500€: Japón (2.690€), Perú (2.540€)." },
      { heading: "Paso 3: ¿Qué tipo de viaje quieres?", body: "Aventura: Costa Rica, Islandia, Perú. Volcanes, trekkings, naturaleza salvaje.\n\nPlaya: Tailandia, Grecia, Maldivas, Bali. Sol, mar y relax.\n\nCultural: Japón, Egipto, Marruecos, India. Historia, gastronomía, tradiciones.\n\nNieve: Laponia, Islandia. Auroras boreales, huskies, experiencias árticas.\n\nSi no lo tienes claro, Tailandia es la opción más versátil: combina cultura, playa y aventura en un solo viaje.", cta: { text: "Explorar tipos de viaje", href: "/tipos/aventura" } },
    ],
  },
  {
    slug: "viajar-grupo-verano-guia-2026",
    title: "Viajar en grupo en verano: guía completa 2026",
    excerpt: "Todo sobre viajes en grupo para jóvenes en verano 2026: destinos, fechas, precios y consejos para aprovechar al máximo.",
    metaDescription: "Guía completa de viajes en grupo para verano 2026: 10 destinos, fechas, precios desde 990€ y consejos. Para jóvenes de 20-35 años.",
    category: "Destinos",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Grupo de jóvenes viajeros en verano",
    date: "22 Ene 2026",
    dateISO: "2026-01-22",
    readTime: "7 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["brasil", "grecia", "tailandia", "bali", "vietnam"],
    relatedSlugs: ["destinos-baratos-jovenes", "mejores-destinos-primer-viaje-grupo"],
    tags: ["viajes verano 2026", "viajes grupo verano", "destinos verano jóvenes", "verano 2026"],
    sections: [
      { heading: "Verano 2026: la temporada grande", body: "El verano es la época con más variedad de destinos, más plazas y más ganas de viajar. De junio a agosto tienes la oportunidad de vivir el viaje de tu vida con un grupo de jóvenes de tu edad. En Travelhood ofrecemos 10 destinos en verano con coordinador en destino y todo organizado.\n\nPero ojo: el verano es también la temporada que más rápido se llena. Reservar con 3-4 meses de antelación es clave." },
      { heading: "Los 10 destinos de verano 2026", body: "Brasil (agosto, 12 días, desde 1.150€ promo): playas, samba y Rio.\nTailandia (julio, 12 días, desde 1.190€): templos, islas, street food.\nPerú (julio, 14 días, desde 1.490€): Machu Picchu y gastronomía.\nCosta Rica (agosto, 12 días, desde 1.390€): volcanes y biodiversidad.\nGrecia (junio, 10 días, desde 990€): islas y Mediterráneo.\nMéxico (julio, 13 días, desde 1.290€): cenotes, pirámides y playa.\nBali (agosto, 12 días, desde 1.290€): arrozales y volcanes.\nZanzíbar (agosto, 10 días, desde 1.190€): playas y cultura swahili.\nVietnam (agosto, 14 días, desde 1.190€): Ha Long y street food.\nMaldivas (junio, 8 días, desde 1.390€): paraíso cristalino.", cta: { text: "Ver viajes de verano", href: "/temporada/verano" } },
      { heading: "¿Cuándo reservar para verano?", body: "La regla de oro: cuanto antes, mejor. Los viajes de julio y agosto se llenan 3-4 meses antes. Los vuelos suben de precio a medida que se acerca la fecha.\n\nTimeline recomendado:\n- Enero-febrero: reserva el viaje y el vuelo.\n- Marzo-abril: prepara documentación (visados, vacunas).\n- Mayo: últimos preparativos y maleta.\n- Junio-agosto: ¡a viajar!" },
      { heading: "Consejos para el verano", body: "1. El calor no es problema si estás preparado: ropa ligera, protector solar, hidratación constante.\n2. Los destinos del sudeste asiático tienen temporada de lluvias en verano, pero llueve fuerte y corto — no arruina el viaje.\n3. Si tu presupuesto es ajustado, Grecia en junio (desde 990€ + 200€ vuelo) es la opción más económica.\n4. Si tienes flexibilidad, septiembre es más barato y con menos gente que julio-agosto.", cta: { text: "Ver ofertas de verano", href: "/ofertas" } },
    ],
  },
  {
    slug: "viajes-baratos-grupo-menos-1000",
    title: "Viajes baratos en grupo: destinos por menos de 1.000€",
    excerpt: "Sí, puedes viajar en grupo organizado por menos de 1.000€ (viaje + vuelo). Estos son los destinos que lo hacen posible.",
    metaDescription: "Viajes en grupo para jóvenes por menos de 1.000€ total en 2026. Marruecos, Grecia y opciones económicas con coordinador incluido.",
    category: "Guías",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Viajes económicos en grupo para jóvenes",
    date: "20 Ene 2026",
    dateISO: "2026-01-20",
    readTime: "5 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["marruecos", "grecia", "portugal"],
    relatedSlugs: ["destinos-baratos-jovenes", "cuanto-cuesta-viaje-grupo-presupuesto"],
    tags: ["viajes baratos grupo", "menos de 1000€", "viajes económicos jóvenes", "viajes low cost grupo"],
    sections: [
      { heading: "Viajar en grupo no tiene por qué ser caro", body: "Existe la idea de que los viajes organizados son caros. La realidad es que un viaje en grupo puede costarte menos que hacerlo por tu cuenta, gracias a la negociación colectiva de hoteles, transportes y actividades. Y hay destinos donde el presupuesto total (viaje + vuelo + gastos) cabe perfectamente en menos de 1.000€." },
      { heading: "Marruecos en puente: desde 840€ todo incluido", body: "El campeón del presupuesto. Un puente de 5 días a Marruecos cuesta:\n- Viaje Travelhood: 590€\n- Vuelo desde España: 50-150€\n- Gastos en destino (5 días): 100-150€\n- Total: 740-890€\n\nY hablamos de Marrakech, Atlas, Sahara o costa atlántica. Con coordinador, alojamiento en riads y transporte incluido.", cta: { text: "Ver viajes a Marruecos", href: "/destino/marruecos" } },
      { heading: "Grecia en junio: el Mediterráneo más accesible", body: "Grecia en junio (10 días) es otra opción imbatible:\n- Viaje Travelhood: 790€ (puente mayo) o 990€ (junio)\n- Vuelo desde España: 100-250€\n- Gastos (6-10 días): 200-300€\n- Total puente: 1.090-1.340€ / Junio: 1.290-1.540€\n\nEl puente de mayo a Grecia roza los 1.000€ si encuentras vuelo barato. Atenas, Santorini y Mykonos incluidos.", cta: { text: "Ver viajes a Grecia", href: "/destino/grecia" } },
      { heading: "Trucos para bajar el presupuesto", body: "1. Reserva con early bird: muchos viajes tienen descuento por reserva anticipada (hasta -200€).\n2. Busca vuelos en martes/miércoles y con antelación.\n3. Viaja en temporada media (mayo, junio, septiembre, octubre): los vuelos y el viaje son más baratos.\n4. Aprovecha puentes: los viajes de 5-6 días son los más económicos.\n5. Mira nuestra página de ofertas: las últimas plazas a veces tienen descuento.", cta: { text: "Ver ofertas actuales", href: "/ofertas" } },
    ],
  },
  {
    slug: "que-llevar-maleta-viaje-aventura",
    title: "Qué llevar en la maleta para un viaje de aventura",
    excerpt: "La lista actualizada 2026 de lo imprescindible para un viaje de aventura de 10-15 días: ropa, electrónica, documentos y trucos.",
    metaDescription: "Lista completa 2026 para la maleta de un viaje de aventura en grupo: ropa técnica, electrónica, documentos y trucos de viajeros expertos.",
    category: "Guías",
    image: "/images/hero-laponia.jpg",
    imageAlt: "Mochila preparada para viaje de aventura",
    date: "15 Ene 2026",
    dateISO: "2026-01-15",
    readTime: "5 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["islandia", "costa-rica", "peru"],
    relatedSlugs: ["preparar-maleta-viaje-aventura", "como-elegir-primer-viaje-grupo"],
    tags: ["maleta viaje aventura", "qué llevar viaje", "lista equipaje 2026", "mochila aventura"],
    sections: [
      { heading: "La maleta perfecta en 2026", body: "Preparar la maleta para un viaje de aventura genera más estrés del necesario. La regla es simple: lleva menos de lo que crees que necesitas. En el 90% de los casos, lo que te sobra pesa más que lo que te falta. Y si te falta algo, lo compras en destino (probablemente más barato).\n\nEsta lista está actualizada con las recomendaciones de nuestros coordinadores y viajeros repetidores." },
      { heading: "Ropa: la fórmula 3-2-1", body: "3 camisetas técnicas de secado rápido (no algodón).\n2 pantalones largos convertibles (se convierten en cortos con cremallera).\n1 forro polar ligero o sudadera.\n1 chubasquero compacto.\nRopa interior para 5-6 días (lavas en destino).\n1 bañador.\n1 outfit casual para cenar/salir.\n\nZapatos: unas zapatillas de trekking cómodas (ya usadas, nunca estrenes) y unas chanclas. Máximo 2 pares de calzado." },
      { heading: "Electrónica y documentos", body: "Móvil con eSIM o SIM local (te indicamos cuál comprar).\nBatería externa de 10.000 mAh mínimo.\nAdaptador universal de enchufes.\nCargador rápido.\nAuriculares.\n\nDocumentos: pasaporte (6 meses validez mínima), copia digital en el móvil, tarjeta sanitaria europea si aplica, seguro de viaje (incluido con Travelhood).\n\nFotos: el móvil es suficiente. Si llevas cámara, que sea compacta." },
      { heading: "Botiquín y extras", body: "Ibuprofeno/paracetamol.\nAntidiarreico (Fortasec).\nTiritas y desinfectante.\nProtector solar SPF50.\nRepelente de mosquitos (DEET 50%).\nPastillas potabilizadoras (por si acaso).\n\nNo lleves: secador de pelo (los alojamientos tienen), toalla grande (lleva una de microfibra si acaso), más de 2 libros (Kindle o móvil), plancha, exceso de \"por si acasos\".", cta: { text: "Ver destinos de aventura", href: "/tipos/aventura" } },
    ],
  },
  {
    slug: "viajes-grupo-jovenes-2026-guia",
    title: "Viajes en grupo para jóvenes 2026 — Guía completa",
    excerpt: "Todo lo que necesitas saber sobre viajes en grupo para jóvenes de 20-35 años en 2026: destinos, precios, cómo funcionan y por qué son tendencia.",
    metaDescription: "Guía completa de viajes en grupo para jóvenes en 2026. Destinos, precios desde 590€, cómo funcionan, qué incluyen y por qué son la mejor forma de viajar de 20 a 35 años.",
    category: "Guías",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Grupo de jóvenes viajeros de 20-35 años explorando un destino juntos",
    date: "8 Mar 2026",
    dateISO: "2026-03-08",
    readTime: "10 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "marruecos", "japon", "bali", "grecia"],
    relatedSlugs: ["mejores-destinos-primer-viaje-grupo", "cuanto-cuesta-viaje-grupo-presupuesto"],
    tags: ["viajes en grupo jóvenes", "viajes grupo 2026", "viajes organizados jóvenes", "viajes 20-35 años"],
    sections: [
      { heading: "¿Qué es un viaje en grupo para jóvenes?", body: "Un viaje en grupo para jóvenes no es un tour de autobús con guía y paraguas. Es una forma de viajar diseñada para personas de 20 a 35 años que quieren explorar el mundo con un grupo reducido (12-18 personas), itinerarios de aventura y un coordinador que se encarga de la logística.\n\nEn 2026, más de 15.000 jóvenes españoles viajaron en grupo organizado. La tendencia crece un 40% anual, impulsada por el deseo de experiencias compartidas, seguridad y la facilidad de no planificar nada.\n\nLa diferencia con viajar por tu cuenta: tú solo eliges destino y haces la maleta. El resto está resuelto." },
      { heading: "¿Cómo funcionan los viajes en grupo?", body: "El proceso es sencillo:\n\n1. Eliges destino y fechas en la web.\n2. Reservas tu plaza con un depósito.\n3. Reservas tu vuelo (te recomendamos opciones).\n4. Te añadimos al grupo de WhatsApp 2-3 semanas antes.\n5. Llegas al aeropuerto de destino, conoces al grupo y al coordinador.\n6. Desde ese momento, todo está organizado: alojamiento, transporte, actividades.\n\nEl coordinador de Travelhood viaja contigo todo el viaje. No es un guía turístico: es alguien que conoce el destino, gestiona la logística, resuelve imprevistos y se asegura de que el grupo funcione." },
      { heading: "Destinos y precios en 2026", body: "Travelhood ofrece 25 destinos en 2026 con precios desde 590€ por persona (sin vuelo):\n\nEconómicos (590-990€): Marruecos, Grecia, Portugal, Egipto.\nMedio (990-1.290€): Tailandia, Bali, Vietnam, México, Colombia, Cuba.\nPremium (1.290-1.590€): Japón, Perú, Costa Rica, Maldivas, Islandia.\n\nTodos incluyen alojamiento, transporte, coordinador y seguro. El vuelo se reserva aparte para que encuentres el mejor precio desde tu ciudad.\n\nEl presupuesto total medio (viaje + vuelo + gastos) es de 1.500-2.200€ para un viaje de 10-14 días.", cta: { text: "Ver todos los destinos y precios", href: "/viajes/" } },
      { heading: "¿Para quién es este tipo de viaje?", body: "Los viajes en grupo para jóvenes son para ti si:\n\n- Tienes entre 20 y 35 años.\n- Quieres viajar pero no tienes con quién ir (el 70% vienen solos).\n- Prefieres que alguien se encargue de la logística.\n- Buscas experiencias auténticas, no turismo de masas.\n- Quieres conocer gente nueva con intereses similares.\n\nNo son para ti si prefieres improvisar totalmente, si buscas un resort all-inclusive o si quieres viajar sin ningún tipo de estructura. Nuestros viajes tienen un itinerario, pero con flexibilidad y tiempo libre cada día." },
      { heading: "Qué incluye y qué no incluye", body: "Incluido en todos los viajes:\n✓ Alojamiento completo (hoteles, riads, lodges según destino)\n✓ Transporte interno (furgoneta, tren, barca)\n✓ Coordinador Travelhood 24h\n✓ Actividades y experiencias del itinerario\n✓ Seguro de viaje\n✓ Extras según destino (Japan Rail Pass, noche en Sahara, etc.)\n\nNo incluido:\n✗ Vuelo internacional\n✗ Comidas no especificadas (varía por destino)\n✗ Gastos personales (souvenirs, propinas, extras opcionales)", cta: { text: "Ver qué incluye cada viaje", href: "/como-funciona/" } },
      { heading: "Por qué 2026 es el año de viajar en grupo", body: "El viaje en grupo para jóvenes ha dejado de ser una alternativa para convertirse en la opción preferida. Las razones son claras: la economía colaborativa, el deseo de experiencias compartidas y la influencia de las redes sociales han cambiado cómo viajamos.\n\nDatos de Travelhood en 2026:\n- 98% de satisfacción entre viajeros\n- 35% repiten en menos de 12 meses\n- Valoración media: 5/5\n- 70% de viajeros reservan solos\n- 65% son mujeres\n\nSi llevas tiempo pensando en viajar pero no te lanzas, este es el momento. El grupo ya se está formando.", cta: { text: "Reserva tu plaza", href: "/viajes/" } },
    ],
  },
  {
    slug: "cuanto-cuesta-viajar-tailandia-2026",
    title: "¿Cuánto cuesta viajar a Tailandia en 2026? Presupuesto real",
    excerpt: "Desglose completo del presupuesto para viajar a Tailandia en 2026: viaje en grupo, vuelo, comida, actividades y gastos diarios.",
    metaDescription: "¿Cuánto cuesta viajar a Tailandia en 2026? Presupuesto real desglosado: viaje en grupo desde 1.090€, vuelo 500-700€, gastos diarios 20-30€. Guía completa.",
    category: "Guías",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Presupuesto de viaje a Tailandia con templos y playas",
    date: "7 Mar 2026",
    dateISO: "2026-03-07",
    readTime: "7 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "bali", "vietnam"],
    relatedSlugs: ["cuanto-cuesta-viaje-grupo-presupuesto", "guia-tailandia-jovenes"],
    tags: ["cuánto cuesta viajar a tailandia", "presupuesto tailandia 2026", "viaje tailandia precio", "tailandia barato"],
    sections: [
      { heading: "El presupuesto real para Tailandia en 2026", body: "\"¿Cuánto me va a costar Tailandia?\" es la primera pregunta que nos hacen. Y mereces una respuesta sin rodeos: un viaje de 12 días a Tailandia con Travelhood cuesta en total aproximadamente 1.990€. Ese es el presupuesto real, completo, con viaje, vuelo y gastos en destino incluidos.\n\nPero como cada viajero tiene su estilo, vamos a desglosarlo al detalle para que sepas exactamente dónde va cada euro." },
      { heading: "Desglose del viaje en grupo: 1.090€", body: "El precio del viaje con Travelhood para Tailandia es de 1.090€ por persona (con early bird, 1.190€ sin descuento). Este precio incluye:\n\n✓ 11 noches de alojamiento (hoteles y hostels boutique)\n✓ Todos los traslados internos (furgoneta, minibús, lancha a las islas)\n✓ Coordinador Travelhood todo el viaje\n✓ Actividades: templos de Bangkok, mercado flotante, elefantes en Chiang Mai, snorkel en Phi Phi\n✓ Seguro de viaje completo\n\nEs un precio negociado en grupo que por tu cuenta te costaría entre 1.400-1.800€ solo en alojamiento, transporte y actividades.", cta: { text: "Ver viaje a Tailandia", href: "/destino/tailandia/" } },
      { heading: "Vuelo internacional: 500-700€", body: "Los vuelos desde España a Bangkok cuestan entre 500 y 700€ ida y vuelta, dependiendo de cuándo reserves y desde qué ciudad salgas.\n\nConsejos para ahorrar:\n- Reserva con 3-4 meses de antelación: es el sweet spot.\n- Martes y miércoles suelen ser los días más baratos.\n- Vuelos con escala (Qatar Airways, Turkish Airlines) suelen ser 100-150€ más baratos que los directos.\n- Desde Madrid y Barcelona hay más opciones. Desde otras ciudades, busca conexiones con estas." },
      { heading: "Gastos en destino: 250-350€ (12 días)", body: "Tailandia es uno de los países más baratos del mundo para turistas. Tu presupuesto diario en destino será de 20-30€, que incluye:\n\nComida (8-15€/día):\n- Comida callejera: 1-3€ por plato (pad thai, arroz con curry, som tam)\n- Restaurante con aire acondicionado: 5-10€\n- Cerveza local (Chang, Leo): 1-2€\n\nActividades extra (5-10€/día):\n- Masaje tailandés: 5-10€/hora\n- Templos: 0-5€ entrada\n- Mercados nocturnos: compras desde 2-3€\n\nSouvenirs y extras (5-10€/día):\n- Camisetas: 3-5€\n- Elefantes de madera: 2-5€\n- Especias y tés: 1-3€", cta: { text: "Ver presupuesto completo", href: "/presupuesto/tailandia/" } },
      { heading: "Resumen: presupuesto total Tailandia 2026", body: "Viaje Travelhood: 1.090€ (early bird)\nVuelo ida/vuelta: ~600€\nGastos en destino (12 días): ~300€\nTotal: ~1.990€\n\nSon 166€ por día con absolutamente todo incluido: alojamiento, transporte, actividades, vuelo, comida y coordinador. Es difícil encontrar una experiencia mejor por ese precio.\n\nSi tu presupuesto es más ajustado, Marruecos en puente (desde 840€ total) o Grecia (desde 1.440€ total) son alternativas más económicas. Si puedes estirarte, Japón (desde 2.690€ total) es la experiencia que más impacta.", cta: { text: "Reserva tu plaza en Tailandia", href: "/destino/tailandia/" } },
    ],
  },
  {
    slug: "mejor-epoca-viajar-japon",
    title: "¿Cuál es la mejor época para viajar a Japón? Guía por meses",
    excerpt: "Cerezos, otoño, nieve, verano: cada estación ofrece un Japón diferente. Te contamos cuándo ir según lo que buscas.",
    metaDescription: "Mejor época para viajar a Japón en 2026: cerezos en primavera, momiji en otoño, festivales en verano. Guía mes a mes con precios y recomendaciones.",
    category: "Guías",
    image: "/images/hero-japon.jpg",
    imageAlt: "Cerezos en flor en Japón durante primavera",
    date: "6 Mar 2026",
    dateISO: "2026-03-06",
    readTime: "8 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["japon", "tailandia"],
    relatedSlugs: ["guia-japon-jovenes", "mejores-destinos-primer-viaje-grupo"],
    tags: ["mejor época viajar japón", "cuando ir a japón", "cerezos japón", "japón por meses"],
    sections: [
      { heading: "Cada estación, un Japón diferente", body: "Japón es de los pocos países donde la época del año cambia radicalmente la experiencia. No es lo mismo ver Kioto envuelto en cerezos rosas que cubierto de nieve o en pleno festival de verano. Cada estación tiene su magia, y esta guía te ayuda a elegir cuándo ir según lo que buscas.\n\nLa respuesta corta: la mejor época para la mayoría de viajeros es primavera (marzo-mayo) o otoño (octubre-noviembre). Pero sigue leyendo para entender por qué." },
      { heading: "Primavera (marzo-mayo): cerezos en flor", body: "La temporada de sakura (cerezos) es el momento más mágico. Las flores empiezan en el sur a mediados de marzo y avanzan hacia el norte durante 6 semanas. En Tokio y Kioto, el pico suele ser la última semana de marzo y primera de abril.\n\nPros: paisajes inolvidables, temperaturas agradables (15-22°C), hanami (picnics bajo los cerezos).\nContras: es la época más demandada. Vuelos más caros y hay que reservar con mucha antelación.\n\nPrecio viaje: desde 1.390€ (Semana Santa, con early bird).\nVuelo estimado: 700-900€.\nIdeal para: viajeros que buscan la foto perfecta y la experiencia más icónica de Japón.", cta: { text: "Ver viaje a Japón en Semana Santa", href: "/destino/japon/" } },
      { heading: "Verano (junio-agosto): festivales y naturaleza", body: "Junio es temporada de lluvias (tsuyu), pero julio y agosto son meses de festivales espectaculares: fuegos artificiales (hanabi), matsuri con yukata, y naturaleza en su máximo esplendor. Las montañas de Hakone, los Alpes japoneses y Hokkaido son impresionantes.\n\nPros: festivales únicos, Hokkaido sin calor, precios de vuelo moderados.\nContras: calor y humedad intensos en Tokio y Kioto (30-35°C, humedad 80%). Septiembre es la alternativa perfecta.\n\nPrecio viaje: desde 1.490€.\nIdeal para: viajeros que toleran el calor y quieren vivir la cultura festiva japonesa." },
      { heading: "Otoño (octubre-noviembre): momiji y gastronomía", body: "El momiji (hojas de otoño) es tan espectacular como los cerezos pero con menos turistas. Los arces rojos y dorados transforman los templos de Kioto, Nara y Nikko en postales de otro mundo. Noviembre es el pico.\n\nPros: colores increíbles, temperaturas perfectas (10-20°C), menos turistas que en primavera, temporada de cangrejo y comida de otoño.\nContras: los vuelos de octubre son más caros por ser puente en España.\n\nPrecio viaje: desde 1.490€.\nIdeal para: fotógrafos, foodies y quienes prefieren evitar multitudes.", cta: { text: "Ver cuando viajar a Japón", href: "/cuando-viajar-a/japon/" } },
      { heading: "Invierno (diciembre-febrero): nieve y onsen", body: "Japón en invierno es subestimado. Los onsen (baños termales) al aire libre con nieve cayendo son una experiencia sublime. Hokkaido tiene festivales de nieve, Nagano tiene monos bañándose en aguas termales y Tokio en Navidad es luminoso.\n\nPros: pocos turistas, precios más bajos, experiencias únicas (onsen + nieve).\nContras: días cortos, frío intenso en el norte (-5 a 5°C).\n\nIdeal para: viajeros que buscan una experiencia diferente y no les importa el frío." },
      { heading: "Resumen: ¿cuándo ir a Japón?", body: "Cerezos: finales de marzo - inicios de abril. La más icónica.\nOtoño: noviembre. La más fotogénica con menos gente.\nVerano: julio-agosto. Para festivales y naturaleza.\nInvierno: enero-febrero. Para onsen, nieve y tranquilidad.\n\nNuestra recomendación: si es tu primer viaje, primavera en Semana Santa. Si ya has ido, otoño. Si buscas algo único, invierno.\n\nEn Travelhood organizamos viajes a Japón en Semana Santa (14 días, desde 1.390€ con early bird) y en septiembre (14 días, desde 1.490€). Ambas fechas ofrecen las mejores condiciones.", cta: { text: "Ver viajes a Japón", href: "/destino/japon/" } },
    ],
  },
  {
    slug: "tailandia-o-bali-que-elegir",
    title: "¿Tailandia o Bali? Comparativa completa para viajeros",
    excerpt: "Los dos gigantes del sudeste asiático, cara a cara. Precios, experiencias, clima y cuál elegir según lo que buscas.",
    metaDescription: "¿Tailandia o Bali? Comparativa completa 2026: precios, clima, experiencias, comida y qué destino elegir según tu perfil de viajero.",
    category: "Destinos",
    image: "/images/hero-zanzibar.jpg",
    imageAlt: "Comparativa visual entre Tailandia y Bali",
    date: "5 Mar 2026",
    dateISO: "2026-03-05",
    readTime: "8 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["tailandia", "bali"],
    relatedSlugs: ["guia-tailandia-jovenes", "guia-bali-jovenes"],
    tags: ["tailandia o bali", "tailandia vs bali", "comparar destinos asia", "bali o tailandia"],
    sections: [
      { heading: "El duelo del sudeste asiático", body: "\"¿Tailandia o Bali?\" es la pregunta que más nos hacen. Ambos son destinos icónicos del sudeste asiático, ambos tienen playas increíbles y comida espectacular, y ambos son accesibles económicamente. Pero son experiencias muy diferentes.\n\nEsta comparativa te ayuda a decidir con datos reales, no con opiniones subjetivas. Y spoiler: no hay uno mejor que otro. Hay uno mejor para ti." },
      { heading: "Precio: ¿cuál es más barato?", body: "Tailandia gana por poco:\n\nViaje en grupo: Tailandia 1.090€ vs Bali 1.250€\nVuelo: Tailandia ~600€ vs Bali ~700€\nGastos diarios: Tailandia 20-30€ vs Bali 20-25€\nTotal 12 días: Tailandia ~1.990€ vs Bali ~2.150€\n\nLa diferencia es de unos 160€. Tailandia es ligeramente más barata, sobre todo en vuelos y precio base del viaje. Pero en gastos diarios están muy igualados: ambos son destinos muy económicos en destino.", cta: { text: "Comparar precios", href: "/comparar/tailandia-vs-bali/" } },
      { heading: "Experiencia: ¿qué ofrece cada uno?", body: "Tailandia es variedad: templos de Bangkok, montañas de Chiang Mai, islas del sur (Phi Phi, Krabi), comida callejera de nivel mundial. Es un país grande con mucho contraste entre norte y sur. Es más festivo, más urbano y más caótico (en el buen sentido).\n\nBali es profundidad: arrozales de Ubud, volcán Batur al amanecer, templos hindúes en acantilados, yoga, espiritualidad. Es una isla más compacta, más espiritual, más introspectiva. Si Tailandia es una fiesta, Bali es una meditación.\n\nAmbos tienen playas espectaculares, pero de estilos diferentes: Tailandia tiene islas paradisíacas con arena blanca; Bali tiene acantilados dramáticos y playas de surf." },
      { heading: "Clima y mejor época", body: "Tailandia: mejor época noviembre-febrero (fresca y seca). Evitar junio-octubre (monzón, aunque lluvia corta). Semana Santa y verano funcionan bien.\n\nBali: mejor época abril-octubre (seca). Noviembre-marzo es húmeda pero con menos turistas y precios más bajos. Semana Santa y verano (agosto) son ideales.\n\nClave: ambos son compatibles con Semana Santa y verano, las dos temporadas principales de viaje." },
      { heading: "El veredicto: ¿cuál elegir?", body: "Elige Tailandia si:\n- Es tu primer viaje a Asia\n- Quieres variedad (ciudad + montaña + playa)\n- Tu presupuesto es más ajustado\n- Prefieres una experiencia festiva y social\n\nElige Bali si:\n- Buscas algo más espiritual y transformador\n- Te atraen los volcanes y la naturaleza tropical\n- Quieres yoga, meditación o wellness\n- Prefieres una experiencia más íntima y profunda\n\nY si no puedes decidir: empieza por Tailandia (es el debut perfecto en Asia) y deja Bali para tu segundo viaje. Muchos de nuestros viajeros hacen exactamente eso.", cta: { text: "Ver viajes a ambos destinos", href: "/viajes/" } },
    ],
  },
  {
    slug: "opiniones-travelhood-viajeros",
    title: "Opiniones de Travelhood: lo que dicen nuestros viajeros (actualizado 2026)",
    excerpt: "Recopilación de opiniones reales de viajeros de Travelhood. Sin filtros, sin edición: lo que piensan quienes ya han vivido la experiencia.",
    metaDescription: "Opiniones reales de viajeros de Travelhood en 2026. Testimonios con nombre, edad y destino. Valoración 5/5 con 98% de satisfacción.",
    category: "Comunidad",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Viajeros reales de Travelhood compartiendo su experiencia",
    date: "4 Mar 2026",
    dateISO: "2026-03-04",
    readTime: "6 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["brasil", "japon", "zanzibar", "maldivas", "laponia"],
    relatedSlugs: ["como-hacer-amigos-viajando", "por-que-viajar-en-grupo"],
    tags: ["travelhood opiniones", "opiniones travelhood", "reseñas travelhood", "travelhood reviews"],
    sections: [
      { heading: "¿Qué dicen los que ya han viajado con Travelhood?", body: "Antes de reservar un viaje, lo normal es buscar opiniones. ¿Es de fiar? ¿Merece la pena? ¿Cómo es realmente la experiencia? En lugar de contártelo nosotros, dejamos que hablen quienes ya lo han vivido.\n\nEstas opiniones son de viajeros reales que han viajado con Travelhood entre 2025 y 2026. Con sus nombres, edades, ciudades y destinos. Sin edición, sin filtros." },
      { heading: "Lo que más valoran los viajeros", body: "Después de analizar más de 500 opiniones, hay 4 temas que se repiten:\n\n1. El grupo: \"Fui sin conocer a nadie. Volví con gente que ya considero amigos\" — Laura, 28 años, Madrid (Brasil).\n\n2. El coordinador: \"Tener a alguien que se encarga de todo en destino es un game changer\" — Pablo, 25 años, Barcelona (Laponia).\n\n3. Las experiencias: \"Japón me volaba la cabeza cada día. Y el grupo hizo que fuera 10 veces mejor\" — Ana, 31 años, Valencia.\n\n4. La repetición: \"Repetí con Travelhood. La primera vez fui solo, la segunda convencí a dos amigos\" — David, 30 años, Málaga." },
      { heading: "Las preguntas que te haces antes de reservar", body: "\"¿Y si el grupo es raro?\" — En más de 500 viajeros, no hemos tenido un solo caso de alguien que no conectara. La selección por edad (20-35) y el tipo de viaje crean afinidad natural.\n\n\"¿Es caro para lo que ofrece?\" — Cuando comparas con organizarlo por tu cuenta, el grupo sale igual o más barato. Y con coordinador, seguro y experiencias incluidas.\n\n\"¿Podré ir a mi ritmo?\" — Sí. Los itinerarios incluyen tiempo libre y actividades opcionales. No es un campamento militar." },
      { heading: "Datos de satisfacción real", body: "Estos son nuestros números reales a marzo de 2026:\n\n- Valoración media: 5/5\n- Viajeros que repetirían: 98%\n- Viajeros que mantienen el grupo de WhatsApp activo: 80%\n- Viajeros que planifican otro viaje juntos: 35%\n- Viajeros que vinieron solos: 70%\n- Incidentes graves en destino: 0\n\nNo somos perfectos, pero estamos obsesionados con que cada viajero vuelva queriendo repetir.", cta: { text: "Ver todas las opiniones", href: "/opiniones/" } },
      { heading: "¿Listo para ser el próximo en opinar?", body: "La mejor opinión que puedes leer es la que vas a escribir tú después de tu primer viaje. Miles de viajeros ya se han lanzado. El 70% vinieron solos. El 98% repetirían.\n\nEl grupo ya se está formando. Solo falta tu nombre en la lista.", cta: { text: "Elige tu viaje", href: "/viajes/" } },
    ],
  },
  {
    slug: "viajes-semana-santa-2026-precios",
    title: "Viajes Semana Santa 2026 — Destinos y precios actualizados",
    excerpt: "Los mejores viajes en grupo para Semana Santa 2026: Japón, Tailandia, Bali, Marruecos y Egipto. Fechas exactas, precios y plazas.",
    metaDescription: "Viajes Semana Santa 2026 para jóvenes en grupo: Japón con cerezos desde 1.390€, Tailandia desde 1.090€, Marruecos desde 790€. Fechas del 28 marzo al 6 abril.",
    category: "Destinos",
    image: "/images/hero-japon.jpg",
    imageAlt: "Viaje de Semana Santa 2026 a Japón con cerezos en flor",
    date: "3 Mar 2026",
    dateISO: "2026-03-03",
    readTime: "7 min",
    featured: true,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["japon", "tailandia", "bali", "marruecos", "egipto"],
    relatedSlugs: ["destinos-semana-santa-grupo", "cuanto-cuesta-viaje-grupo-presupuesto"],
    tags: ["viajes semana santa 2026", "semana santa 2026 viajes", "destinos semana santa", "viajes grupo semana santa"],
    sections: [
      { heading: "Semana Santa 2026: del 28 de marzo al 6 de abril", body: "Semana Santa 2026 arranca el 28 de marzo y termina el 6 de abril. Son 10 días de vacaciones que, combinados con unos pocos días laborables, permiten viajes de hasta 14 días. Es la primera gran oportunidad del año para un viaje largo.\n\nEn Travelhood tenemos 5 destinos preparados con fechas cerradas, coordinador confirmado y plazas limitadas. Las reservas se cierran a mediados de marzo o cuando se completan los grupos." },
      { heading: "Japón con cerezos en flor: desde 1.390€", body: "Semana Santa 2026 coincide con la temporada de sakura (cerezos en flor) en Japón. Es el momento más fotografiado y más mágico del país: Tokio, Kioto, Osaka y Nara envueltos en flores rosas.\n\n14 días (27 marzo - 9 abril)\nDesde 1.390€ (early bird) / 1.490€ (precio regular)\nIncluye: Japan Rail Pass, alojamiento, coordinador, actividades\nVuelo estimado: 700-900€\nPlazas: últimas disponibles\n\nEs el viaje más demandado de Semana Santa. Si te interesa, no esperes.", cta: { text: "Ver viaje a Japón", href: "/destino/japon/" } },
      { heading: "Tailandia, Bali y más destinos asiáticos", body: "Tailandia (12 días, desde 1.090€ con early bird): el destino más versátil. Bangkok, Chiang Mai y playas del sur. Clima perfecto en estas fechas.\n\nBali (13 días, desde 1.250€): arrozales, volcanes y playas. Abril es final de la temporada seca — buen clima y menos turistas.\n\nAmbos destinos están en su mejor momento climático durante Semana Santa y los vuelos son más baratos que en verano.\n\nVuelo estimado: Tailandia ~600€, Bali ~700€.", cta: { text: "Ver viajes a Asia", href: "/destinos/asia/" } },
      { heading: "Marruecos y Egipto: cercanos e impactantes", body: "Marruecos (9 días, desde 790€ con early bird): Marrakech, desierto del Sahara, Atlas y costa atlántica. A 2 horas de vuelo, es la opción más accesible y económica. Vuelo: 100-200€.\n\nEgipto (10 días, desde 990€ con oferta): Pirámides, crucero por el Nilo, Luxor y Abu Simbel. 5.000 años de historia en 10 días. Vuelo: 300-500€.\n\nSi buscas impacto cultural máximo con presupuesto contenido, estos dos son tu mejor apuesta para Semana Santa.", cta: { text: "Ver todos los destinos", href: "/temporada/semana-santa/" } },
      { heading: "¿Cuándo reservar para Semana Santa?", body: "La respuesta corta: ya. Los viajes de Semana Santa se llenan 2-3 meses antes. Los vuelos suben a medida que se acerca la fecha.\n\nTimeline:\n- Enero-febrero: reserva el viaje y compra el vuelo\n- Marzo: últimos preparativos (visados, vacunas, maleta)\n- 27-29 marzo: ¡sales!\n\nSi estás leyendo esto en marzo y aún no has reservado, consulta plazas disponibles. Algunos destinos pueden estar completos.", cta: { text: "Ver plazas disponibles", href: "/viajes/" } },
    ],
  },
  {
    slug: "mejores-viajes-agosto-2026",
    title: "Los 7 mejores viajes para hacer en agosto 2026",
    excerpt: "Los destinos que mejor funcionan en agosto para viajes en grupo: clima, precios y por qué agosto es el mes estrella.",
    metaDescription: "Los 7 mejores viajes en grupo para agosto 2026: Brasil, Tailandia, Bali, Costa Rica, Zanzíbar, México y Perú. Precios, clima y plazas.",
    category: "Destinos",
    image: "/images/hero-brasil.jpg",
    imageAlt: "Viajes en grupo para agosto 2026",
    date: "2 Mar 2026",
    dateISO: "2026-03-02",
    readTime: "7 min",
    featured: false,
    author: { name: "Travelhood", role: "Equipo editorial" },
    relatedDestinations: ["brasil", "tailandia", "bali", "costa-rica", "zanzibar"],
    relatedSlugs: ["viajar-grupo-verano-guia-2026", "destinos-baratos-jovenes"],
    tags: ["viajes agosto 2026", "viajes agosto", "destinos agosto", "viajes grupo agosto"],
    sections: [
      { heading: "Agosto: el mes rey de los viajes", body: "Agosto es cuando la mayoría de jóvenes españoles tienen vacaciones largas. Es el mes con más viajeros, más opciones y más energía en los grupos. En Travelhood, agosto es nuestra temporada alta: 7 destinos con salidas confirmadas, coordinadores asignados y grupos formándose.\n\nEstos son los 7 mejores viajes que puedes hacer en agosto de 2026, ordenados por valoración de viajeros anteriores." },
      { heading: "1. Brasil — La experiencia más completa (12 días, desde 1.150€)", body: "Brasil en agosto es temporada seca y temperaturas agradables (25-28°C). Río de Janeiro, playas de Florianópolis, cascadas de Iguazú y la energía brasileña en estado puro. Es el viaje que más engacha en verano: cultura, playa, aventura y fiesta.\n\nVuelo estimado: 700-850€.\nTotal estimado: ~2.100€.", cta: { text: "Ver viaje a Brasil", href: "/destino/brasil/" } },
      { heading: "2. Bali y 3. Tailandia — Los reyes de Asia", body: "Bali en agosto (12 días, desde 1.290€): temporada seca, cielos despejados, volcán Batur al amanecer con vistas infinitas. Es el mes perfecto para Bali. Vuelo: ~700€. Total: ~2.150€.\n\nTailandia en agosto (12 días, desde 1.190€): técnicamente es temporada de lluvias, pero en la práctica llueve 1-2 horas al día y el resto es sol. Menos turistas y precios más bajos. Vuelo: ~600€. Total: ~2.050€.\n\nAmbos son destinos seguros para agosto con experiencias muy diferentes: Bali para espiritualidad y naturaleza, Tailandia para variedad y street food.", cta: { text: "Comparar Tailandia vs Bali", href: "/comparar/tailandia-vs-bali/" } },
      { heading: "4. Costa Rica y 5. México — La aventura latinoamericana", body: "Costa Rica en agosto (12 días, desde 1.390€): temporada verde (llueve por la tarde pero la naturaleza es exuberante). Volcanes, selva, playas del Caribe. La biodiversidad en su máxima expresión. Vuelo: ~800€. Total: ~2.490€.\n\nMéxico en agosto (13 días, desde 1.290€): cenotes cristalinos, pirámides mayas, playas del Caribe y gastronomía de talla mundial. Clima caluroso pero con refrescos naturales (cenotes, mar). Vuelo: ~700€. Total: ~2.250€.", cta: { text: "Ver viajes a Latinoamérica", href: "/destinos/america/" } },
      { heading: "6. Zanzíbar y 7. Perú — Las joyas de agosto", body: "Zanzíbar en agosto (10 días, desde 1.190€): el secreto mejor guardado. Playas de arena blanca, cultura swahili, snorkel en Mnemba y el Stone Town más auténtico. Agosto es temporada seca perfecta. Vuelo: ~600€. Total: ~1.950€.\n\nPerú en agosto (14 días, desde 1.490€): temporada seca en los Andes, el mejor momento para Machu Picchu. Cielos despejados, noches estrelladas en el Valle Sagrado y Lima gastronómica. Vuelo: ~800€. Total: ~2.540€.", cta: { text: "Ver viajes de agosto", href: "/temporada/verano/" } },
      { heading: "Consejos para viajar en agosto", body: "1. Reserva pronto: agosto se llena 3-4 meses antes. Si lees esto en marzo-abril, es el momento ideal.\n2. Los vuelos suben en julio-agosto. Busca con 3-4 meses de antelación y mira vuelos con escala.\n3. Haz la maleta ligera: todos los destinos de agosto son cálidos.\n4. Si tu presupuesto es ajustado, Zanzíbar (~1.950€ total) y Tailandia (~2.050€ total) son las mejores opciones.\n5. Si septiembre te cuadra mejor, considera mover las fechas: mismos destinos, menos gente y a veces más barato.", cta: { text: "Ver todos los viajes de verano", href: "/temporada/verano/" } },
    ],
  },
]

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug)
}

export function getRelatedPosts(currentSlug: string): BlogPost[] {
  const current = getBlogPost(currentSlug)
  if (!current) return []
  return current.relatedSlugs
    .map((s) => getBlogPost(s))
    .filter((p): p is BlogPost => p !== undefined)
}

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter((p) => p.featured)
}

export function getPostsByCategory(category: string): BlogPost[] {
  if (category === "Todos") return blogPosts
  return blogPosts.filter((p) => p.category === category)
}
